'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'..','public','discovery.js'),'utf8');
function functionSource(name){const marker=new RegExp(`(?:async\\s+)?function\\s+${name}\\s*\\(`),match=marker.exec(source);assert.ok(match,`${name} missing`);const start=match.index;let brace=source.indexOf('{',start),depth=0,quote=null,template=false;for(let i=brace;i<source.length;i++){const ch=source[i],prev=source[i-1];if(quote){if(ch===quote&&prev!=='\\')quote=null;continue;}if(template){if(ch==='`'&&prev!=='\\')template=false;continue;}if(ch==='"'||ch==="'"){quote=ch;continue;}if(ch==='`'){template=true;continue;}if(ch==='{')depth++;if(ch==='}'&&--depth===0)return source.slice(start,i+1);}throw Error(`${name} not closed`);}
function response(ok,payload,status=ok?200:503){return{ok,status,json:async()=>payload};}
function review(overrides={}){const submission={id:'submission-1',submission_number:2,submitted_at:'2026-09-01T00:00:00Z'},answer={question_id:'q1',question_text:'Annual write-offs?',canonical_input:'annualWriteOff',answer_text:'125000'},event={id:'event-1',event_type:'prospect_submitted',discovery_submission_id:'submission-1',canonical_input:'annualWriteOff'};return{submission,answers:[answer],selectedScenario:{isCurrent:true,isClosed:false,canEdit:true},rows:[{canonicalInput:'annualWriteOff',answer,event,currentValue:100000,status:'AVAILABLE',conflictingAnswers:[]}],history:{selectedScenario:{isCurrent:true,isClosed:false,canEdit:true},inputs:{}},...overrides};}
function runtime(responses){const appended=[],toasts=[],body={scrollTop:0},document={getElementById:()=>null,createElement:()=>({id:'',className:'',innerHTML:'',querySelector:()=>body}),body:{appendChild(node){appended.push(node);}}},context={window:{_calcScenarioId:'scenario-1',CITransientOverlays:{suspend:()=> 'overlay-token',restore:()=>{}}},document,console,Date,Number,encodeURIComponent,showToast:message=>toasts.push(message),escapeHtml:value=>String(value??'').replace(/[&<>"']/g,''),discoveryAnswers:{},apiFetch:async()=>responses.shift()};context.window.window=context.window;vm.createContext(context);vm.runInContext(`let latestSubmittedEvidence=null;let latestSubmittedEvidenceLoadError=null;let prospectEvidenceOverlayToken=null;${functionSource('loadLatestSubmittedEvidence')}\n${functionSource('prospectEvidenceAction')}\n${functionSource('renderProspectEvidenceModal')}\n${functionSource('applyDiscoveryToCalc')}\nglobalThis.run=applyDiscoveryToCalc;`,context);return{run:context.run,appended,toasts,context};}

test('every Review Prospect Answers button opens the evidence comparison and history has its own label',()=>{const buttons=[...source.matchAll(/<button[^>]*onclick="([^"]+)"[^>]*>([\s\S]*?)<\/button>/g)].map(m=>({handler:m[1],label:m[2].replace(/<[^>]+>|&#\d+;|&[a-z]+;/gi,' ').replace(/\s+/g,' ').trim()}));const reviews=buttons.filter(x=>x.label.includes('Review Prospect Answers'));assert.equal(reviews.length,2);assert.ok(reviews.every(x=>x.handler==='applyDiscoveryToCalc()'));const historyLaunches=buttons.filter(x=>x.handler==='openSubmissionHistory()'&&!x.label.includes('All submissions'));assert.ok(historyLaunches.length>=1);assert.ok(historyLaunches.every(x=>x.label.includes('Submission History')));});
test('successful authoritative review response renders a visible Review Prospect Evidence modal',async()=>{const r=runtime([response(true,review())]);await r.run();assert.equal(r.appended.length,1);assert.equal(r.appended[0].id,'prospectSyncModal');assert.equal(r.appended[0].className,'modal-overlay open');assert.match(r.appended[0].innerHTML,/<h2>Review Prospect Evidence<\/h2>/);assert.match(r.appended[0].innerHTML,/Use Prospect Value/);assert.match(r.appended[0].innerHTML,/Current working value/);});
test('prospect evidence and submission history use the visible modal state',()=>{assert.match(source,/modal\.id='prospectSyncModal';modal\.className='modal-overlay open'/);assert.match(source,/modal\.id='submissionHistoryModal';modal\.className='modal-overlay open'/);const css=fs.readFileSync(path.join(__dirname,'..','public','style.css'),'utf8');assert.match(css,/\.modal-overlay\.open\s*\{\s*display:flex;/);});
test('API failure and successful no-submission response use different user messages',async()=>{const failed=runtime([response(false,null,503)]);await failed.run();assert.deepEqual(failed.toasts,['Prospect evidence could not be loaded. Please try again.']);const empty=runtime([response(true,review({submission:null,answers:[],rows:[]}))]);await empty.run();assert.equal(empty.toasts.length,1);assert.match(empty.toasts[0],/No immutable prospect submission/);assert.notEqual(empty.toasts[0],failed.toasts[0]);});
test('view-only evidence remains visible but cannot be applied',async()=>{const payload=review({selectedScenario:{isCurrent:true,isClosed:false,canEdit:false},rows:[{...review().rows[0],status:'READ_ONLY'}]});const r=runtime([response(true,payload)]);await r.run();assert.equal(r.appended.length,1);assert.match(r.appended[0].innerHTML,/Review Prospect Evidence/);assert.doesNotMatch(r.appended[0].innerHTML,/Use Prospect Value/);assert.match(r.appended[0].innerHTML,/view-only access/i);});
test('an immutable submission with no mapped financial values still opens the review modal',async()=>{const r=runtime([response(true,review({answers:[{question_id:'q1',question_text:'Describe the process',canonical_input:null,answer_text:'Manual'}],rows:[]}))]);await r.run();assert.equal(r.appended.length,1);assert.match(r.appended[0].innerHTML,/Review Prospect Evidence/);assert.match(r.appended[0].innerHTML,/no mapped financial values/i);});
test('applying evidence is single-flight, keeps the modal open, and rerenders the applied row',async()=>{const toasts=[],rendered=[],modalBody={scrollTop:317},modal={querySelector:()=>modalBody},button={dataset:{},disabled:false,textContent:'Use Prospect Value'};const context={window:{crypto:{randomUUID:()=> 'apply-once'},renderCalcProspectValueWarning:()=>{}},document:{getElementById:id=>id==='prospectSyncModal'?modal:null},Date,showToast:m=>toasts.push(m),applyValueEvent:async()=>({alreadyApplied:false}),loadLatestSubmittedEvidence:async()=>({}),renderProspectEvidenceModal:o=>rendered.push(o),latestSubmittedEvidence:{submission:{id:'submission-1'}},latestSubmittedEvidenceLoadError:null};vm.createContext(context);vm.runInContext(`${functionSource('applySubmittedEvidence')}\nglobalThis.run=applySubmittedEvidence;`,context);await Promise.all([context.run('annualWriteOff','event-1',button),context.run('annualWriteOff','event-1',button)]);assert.equal(rendered.length,1);assert.equal(rendered[0].scrollTop,317);assert.equal(button.disabled,true);assert.match(toasts[0],/applied and saved/);assert.doesNotMatch(functionSource('applySubmittedEvidence'),/closeProspectSyncModal/);});
