'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const read=f=>fs.readFileSync(path.join(__dirname,'..',f),'utf8');
const adapters=read('public/executive-output-adapters.js'),story=read('public/executive-story.js'),proposal=read('public/proposal.js');
test('unsaved Executive View and PDF use explicit safe Draft Story',()=>{assert.match(story,/buildDraftExecutiveValueStory/);assert.match(adapters,/buildDraftExecutiveValueStory\(\)/);assert.match(adapters,/_internalDraft:gate\.draft\|\|!window\._calcScenarioId/);assert.doesNotMatch(adapters,/legacyExec/);assert.match(adapters,/DRAFT — NOT READY FOR CUSTOMER SHARING/);});
test('saved story failure is fail closed and never invokes legacy customer renderer',()=>{assert.match(adapters,/Executive Value Story could not be loaded/);assert.match(adapters,/Customer output is unavailable/);assert.doesNotMatch(adapters,/catch\(\(\)=>legacy/);});
test('safe draft contains no server evidence or invented persuasive content',()=>{assert.match(story,/customerProof:\[\]/);assert.match(story,/items:\[\]/);assert.match(story,/facts:\[\]/);assert.match(story,/Modeled Value Case/);assert.doesNotMatch(story,/cost of delay|competitive advantage|industry-generated/i);});
test('Proposal PDF composes persisted editorial content with canonical story',()=>{assert.match(adapters,/function proposalHtml/);assert.match(adapters,/p\.situation/);assert.match(adapters,/p\.recommendation/);assert.match(adapters,/p\.investment/);assert.match(adapters,/storyHtml\(story\)/);assert.match(adapters,/story\.economics\.contractMonths/);});
test('Proposal export flushes and validates local state before readiness',()=>{const word=adapters.slice(adapters.indexOf('window.proposalExportWord'),adapters.indexOf('window.proposalPrint')),pdf=adapters.slice(adapters.indexOf('window.proposalPrint'),adapters.indexOf("if(typeof window.shareBusinessCase"));for(const body of [word,pdf]){assert.ok(body.indexOf('flushProposalSave')<body.indexOf('guardExecutiveOutput'));assert.match(body,/saveFailed\|\|local\.conflict\|\|local\.dirty/);}assert.match(proposal,/getProposalOutputState/);});
