'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const read=f=>fs.readFileSync(path.join(__dirname,'..',f),'utf8');
const adapters=read('public/executive-output-adapters.js'),story=read('public/executive-story.js'),proposal=read('public/proposal.js'),proposalBuilder=read('public/proposal-output-builder.js');
test('unsaved Executive View fails closed and customer PDF requires a save',()=>{assert.match(story,/requires a saved governed scenario/);assert.match(adapters,/if\(!window\._calcScenarioId\)\{renderStoryError\(\)/);assert.match(adapters,/Save the scenario before creating a customer PDF/);assert.doesNotMatch(adapters,/buildDraftExecutiveValueStory\(\)|legacyExec/);});
test('saved story failure is fail closed and never invokes legacy customer renderer',()=>{assert.match(adapters,/Executive Value Story could not be loaded/);assert.match(adapters,/Customer output is unavailable/);assert.doesNotMatch(adapters,/catch\(\(\)=>legacy/);});
test('browser cannot build an independent Executive draft or invented persuasive content',()=>{assert.doesNotMatch(story,/calcROI|customerProof:\[\]|Modeled Value Case/);assert.match(story,/requires a saved governed scenario/);assert.doesNotMatch(story,/cost of delay|competitive advantage|industry-generated/i);});
test('Proposal PDF composes persisted editorial content with canonical story and governed investment',()=>{assert.match(adapters,/CIProposalOutputBuilder\.buildProposalOutputHtml/);assert.match(proposal,/CIProposalOutputBuilder\.buildProposalOutputHtml/);assert.match(proposalBuilder,/proposal\.situation/);assert.match(proposalBuilder,/proposal\.recommendation/);assert.doesNotMatch(proposalBuilder,/proposal\.commercialTerms/);assert.match(proposalBuilder,/e\.totalContractInvestment/);assert.doesNotMatch(proposalBuilder,/proposal\.investment/);});
test('Proposal export flushes and validates local state before readiness',()=>{const word=adapters.slice(adapters.indexOf('window.proposalExportWord'),adapters.indexOf('window.proposalPrint')),pdf=adapters.slice(adapters.indexOf('window.proposalPrint'),adapters.indexOf("if(typeof window.shareBusinessCase"));for(const body of [word,pdf]){assert.ok(body.indexOf('flushProposalSave')<body.indexOf('guardExecutiveOutput'));assert.match(body,/saveFailed\|\|local\.conflict\|\|local\.dirty/);}assert.match(proposal,/getProposalOutputState/);});
