'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const read=f=>fs.readFileSync(path.join(__dirname,'..',f),'utf8');
const adapters=read('public/executive-output-adapters.js'),story=read('public/executive-story.js'),proposal=read('public/proposal.js'),proposalBuilder=read('public/proposal-output-builder.js');
test('unsaved Executive View fails closed and customer PDF requires a save',()=>{assert.match(story,/requires a saved governed scenario/);assert.match(adapters,/if\(!window\._calcScenarioId\)\{renderStoryError\(\)/);assert.match(adapters,/Save the scenario before creating a customer PDF/);assert.doesNotMatch(adapters,/buildDraftExecutiveValueStory\(\)|legacyExec/);});
test('saved story failure is fail closed and never invokes legacy customer renderer',()=>{assert.match(adapters,/executive_web\.failed_closed/);assert.match(adapters,/showExecutiveValueStoryUnavailable/);assert.doesNotMatch(adapters,/catch\(\(\)=>legacy/);});
test('browser cannot build an independent Executive draft or invented persuasive content',()=>{assert.doesNotMatch(story,/calcROI|customerProof:\[\]|Modeled Value Case/);assert.match(story,/requires a saved governed scenario/);assert.doesNotMatch(story,/cost of delay|competitive advantage|industry-generated/i);});
test('Proposal PDF composes persisted editorial content with canonical story and governed investment',()=>{const pdf=read('src/exports/proposal-pdf.js');assert.match(adapters,/api\/export\/proposal-pdf/);assert.match(proposal,/CIProposalOutputBuilder\.buildProposalOutputHtml/);assert.match(proposalBuilder,/proposal\.situation/);assert.match(pdf,/proposal\.situation/);assert.match(pdf,/proposal\.recommendation/);assert.doesNotMatch(pdf,/proposal\.commercialTerms/);assert.match(pdf,/economics\.totalContractInvestment/);assert.doesNotMatch(pdf,/proposal\.investment/);});
test('Proposal export flushes and validates local state before readiness',()=>{const preflight=adapters.slice(adapters.indexOf('async function prepareProposalFileExport'),adapters.indexOf('async function requestProposalFile')),body=adapters.slice(adapters.indexOf('async function proposalFileExport'),adapters.indexOf("if(typeof window.shareBusinessCase"));assert.ok(preflight.indexOf('flushProposalSave')<preflight.indexOf('guardExecutiveOutput'));assert.match(preflight,/saveFailed\|\|local\.conflict\|\|local\.dirty/);assert.ok(body.indexOf('prepareProposalFileExport')<body.indexOf('withExecutiveExportDeadline'));assert.match(body,/withExecutiveExportDeadline/);assert.match(proposal,/getProposalOutputState/);});
