'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const registry=require('../src/shared/output-registry'),coverage=require('../config/output-runtime-tests.json'),{SMOKES:OUTPUT_SMOKES}=require('./output-runtime-matrix.test');

test('every active output has a real keyed runtime smoke',()=>{const active=registry.OUTPUTS.filter(x=>x.active).map(x=>x.outputId).sort();assert.deepEqual(Object.keys(OUTPUT_SMOKES).sort(),active);assert.deepEqual([...coverage.activeOutputIds].sort(),active);assert.equal(coverage.runner,'test/output-runtime-matrix.test.js');});

test('roi-methodology-pptx executes with internal chrome and governed null economics',async()=>{
 const texts=[];class Slide{addText(v){texts.push(Array.isArray(v)?v.map(x=>x.text||x).join(' '):String(v));}addShape(){}addImage(){}addTable(rows){texts.push(JSON.stringify(rows));}}
 class Deck{constructor(){this.slides=[];}defineLayout(){}addSlide(){const s=new Slide();this.slides.push(s);return s;}async writeFile(){this.written=true;return new Uint8Array([80,75]);}}
 const economic=require('../public/economic-availability'),window={JSZip:function(){},CIEconomicAvailability:economic,CIBrand:{officeTheme:()=>({W:10,H:5.625,GRAY_BG:'fff',NAVY:'001',WHITE:'fff',FONT:'Arial',LOGO:'logo',LOGO_W:1,LOGO_H:.3,GRAY_TXT:'777',ORANGE:'f80',CYAN:'0aa',DARK_TXT:'222',RED:'f00',GREEN:'080'}),audience:a=>a==='internal'?'Cloud Inventory · Confidential - Internal Use Only':'Cloud Inventory · Confidential and Proprietary',documentTheme:()=>({footer:''}),documentCss:()=>'',logo:()=>''},pptxgen:Deck};
 const context={window,document:{getElementById:()=>null,createElement:()=>({style:{},querySelector:()=>({})}),querySelector:()=>null,body:{appendChild(){}}},ensurePptxReady:async()=>true,pptxgen:Deck,Blob,URL,Date,Intl,console,showToast(){},buildRoiMethodology:()=>({v:{company:'Acme',rep:'Pat'},r:{contractMonths:36,annualBenefit:10,totalContractBenefit:30,totalContractInvestment:null,totalContractNetBenefit:null,totalContractRoi:null,contractPayback:null,totalContractNpv:null,overlapAdj:0},M:v=>economic.hasEconomicValue(v)?'USD '+v:'Not yet established',PC:v=>economic.percent(v),levers:[],alternatives:[]})};
 const fixture=context.buildRoiMethodology();vm.createContext(context);vm.runInContext(read('public/pptx-export.js'),context);vm.runInContext(read('public/deal-export.js'),context);await context.roiMethodologyPPT(fixture);const all=texts.join('\n');assert.match(all,/Confidential - Internal Use Only/);assert.doesNotMatch(all,/Confidential and Proprietary/);assert.match(all,/Not yet established/);assert.doesNotMatch(all,/Total contract ROI[^\n]*0%/);
});

test('roi-methodology-pptx produces a valid OOXML package in the full runtime',async()=>{
 const PptxGenJS=require('pptxgenjs'),JSZip=require('jszip'),economic=require('../public/economic-availability');let generated;
 function RuntimeDeck(){const deck=new PptxGenJS();deck.writeFile=async()=>{generated=await deck.write({outputType:'nodebuffer'});return generated;};return deck;}
 const window={JSZip,CIEconomicAvailability:economic,CIBrand:{officeTheme:()=>({W:10,H:5.625,GRAY_BG:'F4F6F8',NAVY:'102A43',WHITE:'FFFFFF',FONT:'Arial',LOGO:path.join(root,'public','ci-logo-pptx.png'),LOGO_W:.2,LOGO_H:.2,GRAY_TXT:'627D98',ORANGE:'F28C28',CYAN:'00A6A6',DARK_TXT:'243B53',RED:'D64545',GREEN:'16825D'}),audience:a=>a==='internal'?'Cloud Inventory · Confidential - Internal Use Only':'Cloud Inventory · Confidential and Proprietary'},pptxgen:RuntimeDeck};
 const fixture={v:{company:'Acme',rep:'Pat'},r:{contractMonths:36,annualBenefit:10,totalContractBenefit:30,totalContractInvestment:null,totalContractNetBenefit:null,totalContractRoi:null,contractPayback:null,totalContractNpv:null,overlapAdj:0},M:v=>economic.hasEconomicValue(v)?'USD '+v:'Not yet established',PC:v=>economic.percent(v),levers:[],alternatives:[]};
 const context={window,document:{getElementById:()=>null,createElement:()=>({style:{},querySelector:()=>({})}),querySelector:()=>null,body:{appendChild(){}}},ensurePptxReady:async()=>true,pptxgen:RuntimeDeck,Blob,URL,Date,Intl,console,showToast(){}};
 vm.createContext(context);vm.runInContext(read('public/pptx-export.js'),context);vm.runInContext(read('public/deal-export.js'),context);await context.roiMethodologyPPT(fixture);
 assert.ok(Buffer.isBuffer(generated));assert.equal(generated.subarray(0,2).toString(),'PK');const zip=await JSZip.loadAsync(generated);assert.ok(zip.file('[Content_Types].xml'));assert.ok(zip.file('ppt/presentation.xml'));assert.ok(Object.keys(zip.files).some(n=>/^ppt\/slides\/slide\d+\.xml$/.test(n)));
});

test('proposal remains editable but customer output fails closed without adapter',()=>{const window={CIEconomicAvailability:require('../public/economic-availability'),CIBrand:{logo:()=>'',audience:()=>''}},context={window,document:{getElementById:()=>null},localStorage:{getItem:()=>null},Date,setTimeout,clearTimeout,CustomEvent:function(){}};vm.createContext(context);vm.runInContext(read('public/proposal.js'),context);assert.equal(window.proposalPrint,undefined);assert.equal(window.proposalExportWord,undefined);assert.match(read('public/proposal.js'),/proposalPdfBtn[^>]*disabled/);assert.match(read('public/proposal.js'),/AI enhancement unavailable/);});

test('saved-state boundaries and legacy brand/fallback removals are active',()=>{const map=read('public/map.js'),exports=read('public/deal-export.js'),fit=read('public/solution-fit.js'),proposal=read('public/proposal.js');assert.match(map,/getSavedMapForOutput/);assert.match(map,/_mapDirty/);assert.doesNotMatch(exports,/legacyPptActionPlan|pptConfidentialFooter/);assert.match(fit,/flushSolutionFitSave/);assert.match(fit,/await flushSolutionFitSave/);assert.doesNotMatch(proposal,/window\.proposalPrint=print|window\.proposalExportWord=word/);for(const file of ['public/index.html','public/login.html'])assert.doesNotMatch(read(file),/Nextworld Company|Cloud Inventory · Nextworld/);});

test('proposal pricing is modeled-investment authoritative and free-form AI is inactive',()=>{const browser=read('public/proposal.js'),server=read('server.js')+read('src/exports/proposal-docx.js'),state=read('src/shared/proposal-state.js');assert.match(browser,/Modeled Customer Investment/);assert.match(browser,/commercialTerms/);assert.doesNotMatch(browser,/api\/enhance|d\.investment/);assert.match(server,/Modeled Customer Investment/);assert.doesNotMatch(state,/ARRAY_FIELDS=\['investment'\]/);});
