const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {calcROI,ROI_FORMULA_REGISTRY}=require('../src/shared/roi-engine');
const registry=require('../src/shared/questionnaire-roi-registry');
function questionnaire(){let s=fs.readFileSync(path.join(__dirname,'../public/discovery.js'),'utf8');s=s.slice(0,s.indexOf('/* ─────────────────────────────────────────\n   DISCOVERY STATE'));s+='\nthis.api={getProspectQuestions,VE_CORE_QUESTIONS,INDUSTRY_CONTEXT};';const c={window:{},console,buildQuestionnaireRoiRegistry:()=>[]};vm.createContext(c);vm.runInContext(s,c);return c.api;}
const industries=['default','telecom','mfg','construction','oil','distribution','food','retail','mining'];
test('actual visible questionnaires have one canonical financial question per condition',()=>{const api=questionnaire();for(const industry of industries)for(const hasFieldInventory of [false,true]){const rows=api.getProspectQuestions(industry,{hasFieldInventory}).flatMap(s=>s.questions.map(q=>registry.classifyQuestion(q,{industry,section:s.section})));const financial=rows.filter(x=>x.classification==='financial_input');const by={};financial.forEach(q=>(by[q.canonicalInput]??=[]).push(q.id));assert.deepEqual(Object.entries(by).filter(([,ids])=>ids.length>1),[],industry+' field='+hasFieldInventory);assert.deepEqual(registry.validateRegistry(rows,ROI_FORMULA_REGISTRY),[],industry);}});
test('actual VE and context questions have zero direct ROI impact',()=>{const api=questionnaire();for(const q of api.VE_CORE_QUESTIONS.questions.filter(q=>!q.internal))assert.equal(registry.classifyQuestion(q,{section:api.VE_CORE_QUESTIONS.section}).directRoiImpact,false);for(const section of Object.values(api.INDUSTRY_CONTEXT))for(const q of section.questions)assert.equal(registry.classifyQuestion(q,{section:section.section}).directRoiImpact,false);});
test('count semantics, per-person hours conversion, and construction conditional uniqueness',()=>{const api=questionnaire();for(const industry of industries)for(const on of [false,true])for(const section of api.getProspectQuestions(industry,{hasFieldInventory:on}))for(const q of section.questions){if(q.sync==='countDaysYr'){assert.doesNotMatch(q.text,/people-days total/i);assert.match(q.text,/not person-days/i);}if(q.syncConv==='hoursPerWeek')assert.match(q.text,/each affected employee/i);}const c=api.getProspectQuestions('construction',{hasFieldInventory:true}).flatMap(s=>s.questions).filter(q=>q.sync==='fieldLocations');assert.equal(c.length,1);});
test('field-on wording separates central and field pools',()=>{const api=questionnaire(),qs=api.getProspectQuestions('default',{hasFieldInventory:true}).flatMap(s=>s.questions);assert.match(qs.find(q=>q.sync==='inventoryValue').text,/excluding trucks.*field inventory reported separately/i);assert.match(qs.find(q=>q.sync==='annualWriteOff').text,/excluding field losses reported separately/i);});
test('downtime wording excludes separately captured service economics',()=>{const api=questionnaire();for(const industry of industries){const q=api.getProspectQuestions(industry,{hasFieldInventory:false}).flatMap(s=>s.questions).find(q=>q.sync==='downtimeCostPerHr');if(q)assert.match(q.text,/excluding lost sales, service penalties or credits, and expedited freight/i);}});
test('economic classes reconcile exactly and preserve capacity and risk',()=>{const r=calcROI({modelVersion:28,users:10,labor:52000,laborWastePct:.2,mLabor:.5,ordersPerYr:100000,costPerOrder:3,pickRateGainPct:.2,mThroughput:.5,effectiveShrinkBase:100000,mShrinkage:.3,inventory:8000000,carryRate:.25,mCarrying:.2,revenue:10000000,otifBaseline:90,otifTarget:95,contributionMarginPct:.3,mOtif:.2,downtimeEventsYr:10,downtimeHrsPerEvent:2,downtimeCostPerHr:1000,mDowntime:.5});const sum=r.annualDirectCostSavings+r.annualRecoveredContributionMargin+r.annualWorkingCapitalBenefit+r.annualCapacityValue+r.annualRiskAvoidance;assert.equal(sum,r.annualBenefit);assert.equal(r.annualRiskAvoidance,r.downtimeSav);assert.equal(r.annualCapacityValue,0);const cap=calcROI({modelVersion:28,ordersPerYr:100000,costPerOrder:3,pickRateGainPct:.2,mThroughput:.5});assert.equal(cap.annualCapacityValue,cap.annualBenefit);assert.equal(cap.annualDirectCostSavings,0);});
test('count-labor example is not multiplied as people-days twice',()=>{const r=calcROI({modelVersion:28,countDaysYr:12,countPeople:6,labor:52000,mCount:.5});assert.equal(r.countSav,7200);});
test('active Impact Map is v2.8 and generated from authoritative registries',()=>{const s=fs.readFileSync(path.join(__dirname,'../public/impact-map.js'),'utf8');for(const forbidden of ['Version 2.5','Revenue per tech','fieldTechs','addedJobsPerDay','revenuePerJob','Every quantifiable answer','revenue × (target−baseline) × recovery'])assert.ok(!s.includes(forbidden),forbidden);for(const required of ['Contribution margin','Service penalties','Expedite','First-time-fix','Field reconciliation','Economic classes','no direct ROI impact','buildImpactMapModel'])assert.ok(s.includes(required),required);assert.match(s,/getProspectQuestions/);assert.match(s,/classifyQuestion/);assert.match(s,/ROI_FORMULA_REGISTRY/);const d=fs.readFileSync(path.join(__dirname,'../public/discovery.js'),'utf8');assert.doesNotMatch(d,/function downloadImpactMap/);});
test('deal-export has no ghost fields and consumes counted engine drivers',()=>{const s=fs.readFileSync(path.join(__dirname,'../public/deal-export.js'),'utf8');for(const x of ['r.truckRollSav','r.fieldLeakageSav','v.fieldInventoryValue','v.fieldLeakagePct','v.mLeakage','techRevenueSav','fieldTechs','addedJobsPerDay','revenuePerJob','mUtilization'])assert.ok(!s.includes(x),x);assert.match(s,/r\.activeValueDrivers/);assert.match(s,/r\.overlapAdjustments/);assert.match(s,/r\.annualRiskAvoidance/);assert.match(s,/r\.annualCapacityValue/);});
test('generated methodology counted values reconcile to comprehensive v28 engine output',()=>{const input={modelVersion:28,users:20,labor:60000,laborWastePct:.2,mLabor:.4,effectiveShrinkBase:200000,mShrinkage:.3,inventory:8000000,carryRate:.25,mCarrying:.2,invTurnsCurrent:4,invTurnsBenchmark:8,revenue:20000000,otifBaseline:90,otifTarget:95,contributionMarginPct:.3,mOtif:.2,itCost:200000,mIt:.5,downtimeEventsYr:10,downtimeHrsPerEvent:2,downtimeCostPerHr:2000,mDowntime:.25,expediteSpendYr:100000,mExpedite:.25,servicePenaltyCostYr:80000,mServicePenalty:.25,countDaysYr:12,countPeople:6,mCount:.5,ordersPerYr:100000,costPerOrder:3,pickRateGainPct:.2,mThroughput:.5,orderErrorPct:.02,costPerError:100,mAccuracy:.35,repeatVisitsYr:100,costPerTruckRoll:300,mFirstFix:.3,hasFieldInventory:true,fieldInvValue:2000000,fieldLeakageRate:5,mFieldLeakage:.3,fieldLocations:10,fieldReconcilePerYr:4,fieldReconcilePersonHours:8,mFieldCount:.5,invest:125000,contractMonths:36};const src=fs.readFileSync(path.join(__dirname,'../public/deal-export.js'),'utf8'),a=src.indexOf('function buildRoiMethodology()'),b=src.indexOf('/* ── PDF variant',a),c={getVals:()=>input,calcROI,moneyFull:n=>'$'+n,console};vm.createContext(c);vm.runInContext(src.slice(a,b)+'\nthis.build=buildRoiMethodology;',c);const m=c.build(),near=(a,b)=>Math.abs(a-b)<1e-7;assert.ok(near(m.levers.reduce((sum,d)=>sum+d.value,0),m.r.annualBenefit));assert.ok(m.alternatives.some(x=>x.counted===false));assert.ok(near(Object.values(m.categories).slice(0,5).reduce((a,b)=>a+b,0),m.categories.annualEconomicBenefit));});
