'use strict';
/* Real HTTP + PostgreSQL integration coverage. This suite is intentionally
   blocked—not passed—when DATABASE_URL is unavailable. */
const {describe,test,before,after}=require('node:test'),assert=require('node:assert/strict');
const HAS_DB=!!process.env.DATABASE_URL,blocked=HAS_DB?false:'DATABASE_URL unavailable — v6.5.3 PostgreSQL integration is environment-blocked, not passed';
const USER=process.env.TEST_ADMIN_USER||'admin',PASS=process.env.ADMIN_PASSWORD||process.env.TEST_ADMIN_PASS||'CloudInventory2026!';
let server,base,token,db,scenarioA,scenarioB,linkToken,sessionId,question;
async function api(path,{method='GET',auth=token,body}={}){const headers={'Content-Type':'application/json'};if(auth)headers.Authorization='Bearer '+auth;const r=await fetch(base+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});return{status:r.status,json:await r.json().catch(()=>null)};}

if(!HAS_DB){
  test('v6.5.3 real Prospect evidence boundary (7 PostgreSQL/HTTP cases)',{skip:blocked},()=>{});
}else describe('v6.5.3 real Prospect evidence boundary',{concurrency:false},()=>{
  before(async()=>{process.env.NODE_ENV='test';const {runMigrations}=require('../src/migrate');await runMigrations();db=require('../src/db');const {app}=require('../server');server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});base='http://127.0.0.1:'+server.address().port;const login=await api('/api/auth/login',{method:'POST',auth:null,body:{username:USER,password:PASS}});assert.equal(login.status,200);token=login.json.token;
    async function make(label){const company='v653 '+label+' '+Date.now()+' '+Math.random().toString(16).slice(2);const r=await api('/api/scenarios',{method:'POST',body:{name:label,company,data:{name:label,company,industry:'manufacturing',modelVersion:28,annualWriteOff:100000}}});assert.ok([200,201].includes(r.status));return r.json.scenario||r.json;}
    scenarioA=await make('Opportunity A');scenarioB=await make('Opportunity B');
  });
  after(async()=>{if(server)await new Promise(r=>server.close(r));});

  test('anonymous and unsaved requests cannot create a Prospect Link',async()=>{const anon=await api('/api/discovery/sessions',{method:'POST',auth:null,body:{scenarioId:scenarioA.id}});assert.equal(anon.status,401);const unsaved=await api('/api/discovery/sessions',{method:'POST',body:{company:'Injected'}});assert.equal(unsaved.status,400);});
  test('authorized link persists server-derived opportunity schema',async()=>{const made=await api('/api/discovery/sessions',{method:'POST',body:{scenarioId:scenarioA.id,company:'Injected company',industry:'retail',baseId:scenarioB.base_id}});assert.equal(made.status,200);linkToken=made.json.token;sessionId=made.json.sessionId;const row=(await db.query('SELECT * FROM discovery_sessions WHERE id=$1',[sessionId])).rows[0];assert.equal(String(row.scenario_id),String(scenarioA.id));assert.equal(String(row.base_id),String(scenarioA.base_id));assert.notEqual(row.company,'Injected company');const publicView=await api('/api/discovery/sessions/'+linkToken,{auth:null});assert.equal(publicView.status,200);const financial=(await db.query("SELECT question_id,canonical_input FROM discovery_session_questions WHERE discovery_session_id=$1 AND classification='financial_input' AND canonical_input<>'revenue' ORDER BY display_order LIMIT 1",[sessionId])).rows[0];question=publicView.json.questionnaire.flatMap(s=>s.questions).find(q=>q.id===financial.question_id);assert.ok(question);question.serverCanonicalInput=financial.canonical_input;assert.equal(question.classification,undefined);assert.equal(question.canonicalInput,undefined);});
  test('unknown IDs are rejected and entered_by cannot be spoofed',async()=>{const bad=await api('/api/discovery/sessions/'+linkToken+'/answers',{method:'PUT',auth:null,body:{questionId:'forged-question',answer:'999'}});assert.equal(bad.status,400);const good=await api('/api/discovery/sessions/'+linkToken+'/answers',{method:'PUT',auth:null,body:{questionId:question.id,answer:'400000',enteredBy:'rep'}});assert.equal(good.status,200);const row=(await db.query('SELECT entered_by FROM discovery_answers WHERE session_id=$1 AND question_id=$2',[sessionId,question.id])).rows[0];assert.equal(row.entered_by,'prospect');});
  test('client classification tampering cannot manufacture provenance',async()=>{const submitted=await api('/api/discovery/sessions/'+linkToken+'/submit',{method:'POST',auth:null,body:{clientSubmissionId:'v653-first-'+Date.now(),questionContext:{[question.id]:{classification:'financial_input',canonicalInput:'revenue'}}}});assert.equal(submitted.status,201);const events=await db.query('SELECT canonical_input FROM roi_value_events WHERE discovery_submission_id=$1',[submitted.json.submissionId]);assert.equal(events.rowCount,1);assert.equal(events.rows[0].canonical_input,question.serverCanonicalInput);assert.notEqual(events.rows[0].canonical_input,'revenue');});
  test('multiple submissions remain immutable with governed wording',async()=>{const first=(await db.query('SELECT * FROM discovery_submissions WHERE discovery_session_id=$1 ORDER BY submission_number',[sessionId])).rows[0];const firstAnswers=(await db.query('SELECT * FROM discovery_submission_answers WHERE submission_id=$1',[first.id])).rows;await api('/api/discovery/sessions/'+linkToken+'/answers',{method:'PUT',auth:null,body:{questionId:question.id,answer:'475000'}});const second=await api('/api/discovery/sessions/'+linkToken+'/submit',{method:'POST',auth:null,body:{clientSubmissionId:'v653-second-'+Date.now()}});assert.equal(second.status,201);assert.equal(second.json.submissionNumber,2);const still=(await db.query('SELECT * FROM discovery_submission_answers WHERE submission_id=$1',[first.id])).rows;assert.deepEqual(still,firstAnswers);assert.ok(still.every(a=>a.question_text));});
  test('evidence is isolated by base_id across opportunities',async()=>{const foreign=await db.query('SELECT 1 FROM discovery_submissions WHERE base_id=$1 AND discovery_session_id=$2',[scenarioB.base_id,sessionId]);assert.equal(foreign.rowCount,0);const own=await db.query('SELECT 1 FROM discovery_submissions WHERE base_id=$1 AND discovery_session_id=$2',[scenarioA.base_id,sessionId]);assert.equal(own.rowCount,2);});
  test('rotate and revoke require authentication',async()=>{const anonRotate=await api('/api/discovery/sessions/'+linkToken+'/rotate',{method:'PUT',auth:null});assert.equal(anonRotate.status,401);const rotated=await api('/api/discovery/sessions/'+linkToken+'/rotate',{method:'PUT'});assert.equal(rotated.status,200);linkToken=rotated.json.token;const anonRevoke=await api('/api/discovery/sessions/'+linkToken,{method:'DELETE',auth:null});assert.equal(anonRevoke.status,401);const revoked=await api('/api/discovery/sessions/'+linkToken,{method:'DELETE'});assert.ok([200,204].includes(revoked.status));});
});
