'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const {getQuestionnaire,flattenQuestionnaire}=require('../src/shared/questionnaire-definitions');

test('authoritative questionnaire projects the actual visible question definitions',()=>{for(const industry of ['default','telecom','manufacturing','construction','oilgas','distribution','food','retail']){const q=flattenQuestionnaire(industry);assert.ok(q.length>=20,industry);assert.equal(new Set(q.map(x=>x.id)).size,q.length);for(const x of q){assert.ok(x.text);assert.ok(['financial_input','value_engineering','context'].includes(x.classification));}}});
test('field inventory schema is controlled by the saved customer flag',()=>{assert.ok(flattenQuestionnaire('default',{hasFieldInventory:true}).length>flattenQuestionnaire('default',{hasFieldInventory:false}).length);});
test('per-link schema is normalized, immutable, and records legacy backfill',()=>{const sql=read('migrations/030_prospect_evidence_integrity.sql');assert.match(sql,/CREATE TABLE IF NOT EXISTS discovery_session_questions/);assert.match(sql,/BEFORE UPDATE OR DELETE ON discovery_session_questions/);assert.match(sql,/questionnaire_schema_source='legacy_backfill'/);assert.match(sql,/source_scenario_version/);});
test('link creation requires authorized saved scenario and derives server context',()=>{const s=read('server.js'),route=s.slice(s.indexOf("app.post('/api/discovery/sessions'"),s.indexOf('Customer field-inventory flag'));assert.match(route,/if\(!scenarioId\)/);assert.match(route,/scenarioAccess\(req\.user,scenarioId,'edit'\)/);assert.match(route,/SELECT s\.id,s\.base_id,s\.version/);assert.match(route,/ensureSessionQuestions/);assert.doesNotMatch(route,/const \{[^}]*industry[^}]*company[^}]*\} = req\.body/);});
test('public answers reject unknown questions and always use prospect provenance',()=>{const s=read('server.js'),p=read('public/prospect.html'),start=s.indexOf("app.put('/api/discovery/sessions/:token/answers'"),end=s.indexOf('Authenticated rep working-answer path'),route=s.slice(start,end);assert.match(route,/discovery_session_questions/);assert.match(route,/not part of the governed Prospect questionnaire/);assert.match(route,/\[s\.id, questionId, answer \|\| '', 'prospect'\]/);assert.doesNotMatch(route,/enteredBy/);assert.doesNotMatch(p,/JSON\.stringify\(\{ questionId, answer, enteredBy/);});
test('rep answers use a separate authenticated and authorized endpoint',()=>{const s=read('server.js');assert.match(s,/session-records\/:sessionId\/answers',requireAuth/);assert.match(s,/scenarioAccess\(req\.user,s\.scenario_id,'edit'\)/);assert.match(s,/entered_by='rep'/);});
test('submission uses stored question schema and never trusts client question context',()=>{const s=read('server.js'),p=read('public/prospect.html');assert.match(s,/JOIN discovery_session_questions q/);assert.match(s,/context=new Map\(schema\.map/);assert.doesNotMatch(s,/req\.body\?\.questionContext|req\.body\.questionContext/);assert.doesNotMatch(p,/questionContext\s*:/);});
test('review and sync uses only real immutable submission events',()=>{const d=read('public/discovery.js'),start=d.indexOf('async function applyDiscoveryToCalc'),end=d.indexOf('function clearDiscoveryAnswers',start),body=d.slice(start,end);assert.match(body,/loadLatestSubmittedEvidence/);assert.match(body,/discovery_submission_id/);assert.match(body,/applyValueEvent/);assert.doesNotMatch(body,/fieldStates\[[^\]]+\]\s*=\s*['"]confirmed_prospect/);assert.match(body,/Working draft has changed since submission/);});
test('prospect questionnaire renders the stored session schema first',()=>{const p=read('public/prospect.html');assert.match(p,/sessionData\.questionnaire/);assert.match(p,/prospectQuestionnaire\(\)/);});
test('public questionnaire projection hides internal financial mappings',()=>{const schema=read('src/shared/discovery-session-schema.js'),server=read('server.js');const start=schema.indexOf('function groupSessionQuestions'),body=schema.slice(start);assert.doesNotMatch(body,/classification:q\.|canonicalInput:q\.|conversion:q\./);assert.match(server,/questionnaire:groupSessionQuestions\(questions\)/);});
test('discovery exposes submission metadata, history, and revalidation actions',()=>{const d=read('public/discovery.js'),f=read('public/features.js');assert.match(d,/Submitted ' \+ submissionCount/);assert.match(d,/Prospect submitted/);assert.match(d,/View History/);assert.match(d,/Revalidate/);assert.match(f,/prospect_submitted:'Prospect submitted'/);});
test('ROI Model remains v28',()=>{const pkg=JSON.parse(read('package.json'));assert.match(read('src/shared/roi-engine.js'),/modelVersion\s*>=\s*28/);assert.ok(pkg.version);});
