'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const brand=require('../src/shared/brand-system');
const activeFiles=['public/business-case.html','public/prospect.html','public/src/client/api.js','public/style.css','public/exec.css','server.js','public/index.html','public/print.html','public/deal-export.js','public/solution-fit.js','public/proposal.js','public/executive-output-adapters.js','src/email.js'];

test('v6.7.2+ preserves Brand System v1.0 and ROI Model v2.8',()=>{assert.ok(Number(require('../package.json').version.split('.')[0])>=6);assert.equal(brand.brandVersion,'1.0');assert.match(read('src/shared/roi-engine.js'),/modelVersion\s*>=\s*28/);});
test('real active surfaces contain no retired brand or primary-font bypass',()=>{const prohibited=/#00AECF|#042C53|#00AEEF|Helvetica Neue|Calibri|Aptos/i;for(const file of activeFiles)assert.doesNotMatch(read(file),prohibited,file);});
test('customer Business Case uses governed provenance and v2.8-safe wording',()=>{const html=read('public/business-case.html'),ui=read('public/business-case.js'),service=read('src/shared/business-case-publication.js');assert.match(html,/brand-tokens\.css/);assert.match(html,/Customer-provided inputs are supplemented by documented Cloud Inventory model assumptions and approved benchmarks where applicable\./);assert.match(ui,/esc\(d.status\)/);assert.match(service,/d.customerSupported\?'Customer provided':'Cloud Inventory model assumption — validate'/);assert.doesNotMatch(ui,/calcROI|annualBenefit\s*\//);});
test('Prospect time-basis badge uses canonical tokens without palette fallbacks',()=>{const src=read('public/prospect.html');assert.match(src,/\.q-basis-badge\{[^}]*var\(--ci-blue-dark\)[^}]*var\(--ci-info-surface\)[^}]*var\(--ci-blue\)/);assert.doesNotMatch(src,/var\(--cyan,#00AECF\)/i);assert.doesNotMatch(src,/var\(--(?:gray|white)[^,]*,\s*#/i);});
test('session-expiry modal uses shared classes, CSS hover and keyboard focus',()=>{const js=read('public/src/client/api.js'),session=js.slice(js.indexOf('function showSessionExpiryModal'),js.indexOf('async function logout')),css=read('public/style.css');assert.match(session,/className = 'ci-session-expiry'/);assert.match(session,/aria-modal/);assert.match(session,/if \(btn\) btn\.focus\(\)/);assert.match(session,/login\.html\?expired=1/);assert.doesNotMatch(session,/style\.background|#[0-9a-f]{6}(?!;)/i);assert.match(css,/\.ci-session-expiry__action\{[^}]*var\(--ci-blue\)/);assert.match(css,/\.ci-session-expiry__action:hover\{background:var\(--ci-blue-dark\)/);assert.match(css,/\.ci-session-expiry__action:focus-visible/);});
test('shared provenance banner maps status to semantic Brand roles',()=>{const css=read('public/style.css');assert.match(css,/\.e-provenance-banner\{[^}]*var\(--ci-info-surface\)[^}]*var\(--ci-blue\)/);assert.match(css,/\.e-prov-chip-high\{background:var\(--ci-success-surface\);color:var\(--ci-success-text\)/);assert.match(css,/\.e-prov-chip-med\{background:var\(--ci-warning-surface\);color:var\(--ci-warning-text\)/);assert.match(css,/\.e-prov-chip-low\{background:var\(--ci-neutral200\);color:var\(--ci-neutral700\)/);});
test('server purge page resolves every corporate role through shared Brand helpers',()=>{const src=read('server.js'),start=src.indexOf('function purgeHtmlPage'),end=src.indexOf('/* ── Health check',start),purge=src.slice(start,end);assert.match(purge,/brand\.documentTheme\('internal'\)/);assert.match(purge,/brand\.emailTheme\(\)/);for(const role of ['pageBrand.font','pageBrand.success','pageBrand.danger','emailBrand.button','emailBrand.buttonHover','pageBrand.accessibleAccent'])assert.match(purge,new RegExp(role.replace('.','\\.')));assert.doesNotMatch(purge,/#(?:042C53|00AEEF|00AECF|C62828)|Helvetica Neue/i);assert.match(purge,/href="\/"/);});
