'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),JSZip=require('jszip');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const {buildExecutiveValueStory}=require('../src/shared/executive-value-story');
const {buildExecutivePptx}=require('../src/exports/executive-pptx');
function story(){return buildExecutiveValueStory({scenario:{id:'s-v683',base_id:'b-v683',version:3,company:'Northstar Manufacturing',industry:'Manufacturing',solution:'cip',owner_username:'rep',data:{currency:'USD',contractMonths:36,invest:125000,users:42,labor:62000,mLabor:.15,threeWhysAct:'Inventory uncertainty creates operating cost.',threeWhysNow:'A dated operational priority requires action.',threeWhysCi:'Cloud Inventory aligns execution across systems.',revenue:120000000,inventory:18000000}},governance:{evidence:{}},stakeholders:[],discovery:[],solutionFit:null,jointProjectPlan:null,proposal:null});}
test('v6.8.5 version and locked authorities remain aligned',()=>{const pkg=require('../package.json'),knowledge=require('../config/application-knowledge.json');assert.equal(pkg.version,'6.8.5');assert.equal(knowledge.applicationVersion,'6.8.5');assert.equal(knowledge.roiModel.modelVersion,28);assert.equal(knowledge.brandVersion,'1.0');assert.equal(knowledge.knowledgeVersion,'1.0');assert.equal(require('../config/christie-persona.json').personaVersion,'1.0');});
test('landing customer picker uses lightweight authorized list with deterministic recovery states',()=>{const js=read('public/customer-switcher.js');assert.match(js,/fetch\('\/api\/customers'/);assert.match(js,/AbortController/);assert.match(js,/8000/);assert.match(js,/Loading authorized customers/);assert.match(js,/Customers could not be loaded/);assert.match(js,/Retry/);assert.match(js,/No customers yet/);});
test('executive presentation has cover, body, whys, KPI grid, drivers and responsive constraints',()=>{const js=read('public/executive-output-adapters.js'),css=read('public/style.css');for(const token of ['e-cover','e-body','e-whys-grid','e-kpi-grid','e-bar-track','activeDrivers.slice(0,5)','_execPopulateSidebar'])assert.ok(js.includes(token),token);assert.match(css,/max-width:960px/);assert.match(css,/@media\(max-width:480px\)/);assert.doesNotMatch(js,/cost of delay/i);});
test('PDF uses an authenticated server-generated blob with deterministic retry recovery',()=>{const js=read('public/executive-output-adapters.js'),start=js.indexOf('window.downloadPDF=async function'),section=js.slice(start,js.indexOf('window.exportExecutiveWord',start));assert.match(section,/guardExecutiveOutput\('pdf'/);assert.match(section,/\/export-pdf\?/);assert.match(section,/credentials:'same-origin'/);assert.match(section,/await res\.blob\(\)/);assert.match(section,/showOutputRetry/);assert.doesNotMatch(section,/window\.open|print\.html/);});
test('server PowerPoint is a valid branded OOXML deck containing authoritative story facts and draft marking',async()=>{const s=story(),buffer=await buildExecutivePptx(s,{internalDraft:true});assert.ok(Buffer.isBuffer(buffer));assert.equal(buffer.subarray(0,2).toString(),'PK');const zip=await JSZip.loadAsync(buffer),slides=Object.keys(zip.files).filter(x=>/^ppt\/slides\/slide\d+\.xml$/.test(x));assert.ok(slides.length>=5);let xml='';for(const name of slides)xml+=await zip.file(name).async('string');for(const fact of ['Northstar Manufacturing','Executive Value Story','Financial Case','DRAFT','Inventory uncertainty creates operating cost.'])assert.ok(xml.includes(fact),fact);});
test('PowerPoint route is authorized, readiness-governed, report-generated and client is blob-based',()=>{const routes=read('src/routes/scenarios.js'),client=read('public/executive-output-adapters.js');assert.match(routes,/router\.use\(requireAuth\)/);assert.match(routes,/router\.get\('\/:id\/export-pptx'/);assert.match(routes,/executiveReportFor\(req\.user,scenarioId\)/);assert.match(routes,/evaluateExecutiveOutputReadiness\(story,\{outputType:'pptx'\}\)/);assert.match(routes,/presentationml\.presentation/);assert.match(client,/\/export-pptx\?/);assert.match(client,/await res\.blob\(\)/);});
