'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),JSZip=require('jszip');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const registry=require('../src/shared/output-registry'),{buildJppPptx,buildStakeholderPptx}=require('../src/exports/operational-pptx');
test('production auth uses one canonical early requireAuth binding',()=>{const server=read('server.js');assert.equal(server.includes('_reqAuthCompanies'),false,'legacy requireAuth alias must never be reintroduced');const imports=[...server.matchAll(/(?:const|let|var)\s*\{[^}]*\brequireAuth\b[^}]*\}\s*=\s*require\(['"]\.\/src\/middleware\/auth['"]\)/gs)];assert.equal(imports.length,1,'requireAuth must have exactly one canonical auth import');assert.match(imports[0][0],/\{\s*requireAuth\s*,\s*hasRole\s*\}/);const firstProtected=server.search(/app\.(?:get|post|put|patch|delete)\([^\n]+,\s*requireAuth\b/);assert.ok(firstProtected>imports[0].index,'canonical auth import must occur before the first protected route');assert.equal((server.match(/requireAuth\s*:/g)||[]).length,0,'aliased requireAuth destructuring is prohibited');});
test('current authority locks and output registry are complete',()=>{const pkg=require('../package.json'),k=require('../config/application-knowledge.json');assert.equal(pkg.version,'6.9.0');assert.equal(k.applicationVersion,'6.9.0');assert.equal(k.roiModel.modelVersion,28);assert.equal(k.brandVersion,'1.0');assert.equal(k.knowledgeVersion,'1.0');assert.equal(require('../config/christie-persona.json').personaVersion,'1.0');assert.equal(registry.validateRegistry(),true);assert.ok(registry.OUTPUTS.length>=23);for(const x of registry.OUTPUTS){assert.ok(x.authoritativeDataSource);assert.ok(x.logoRole);assert.equal(x.customerSafe,x.audience==='customer');}});
test('production PowerPoint loading is local and filenames are governed',()=>{const ppt=read('public/pptx-export.js'),de=read('public/deal-export.js');assert.doesNotMatch(ppt,/cdn\.jsdelivr|https:\/\//);assert.match(de,/Cloud-Inventory-Internal-Battlecard-/);assert.match(de,/Cloud-Inventory-Internal-Stakeholder-Map-/);});
test('Solution Fit outputs use governed logo and audience labels',()=>{const js=read('public/solution-fit.js');assert.match(js,/CIBrand\.logo\('logoColor'\)/);assert.match(js,/CIBrand\.audience\('customer'\)/);assert.match(js,/CIBrand\.audience\('internal'\)/);});
test('role one-pager active path is governed and Champion Pack is internal',()=>{const js=read('public/deal-export.js'),start=js.indexOf('async function exportGovernedOnePager'),end=js.indexOf('window.exportOnePager=exportGovernedOnePager');assert.ok(start>0&&end>start);const active=js.slice(start,end);assert.match(active,/loadExecutiveValueStory/);assert.doesNotMatch(active,/calcROI|costOfDelay|\/12|generic/);assert.match(read('public/index.html'),/Champion pack[\s\S]{0,100}internal deck/);});
async function validOffice(buffer,kind){assert.ok(Buffer.isBuffer(buffer));assert.ok(buffer.length>5000);const zip=await JSZip.loadAsync(buffer),names=Object.keys(zip.files);assert.ok(names.includes('[Content_Types].xml'));assert.ok(names.includes(`${kind}/presentation.xml`));assert.ok(names.some(n=>n.startsWith(`${kind}/media/`)));const text=await Promise.all(names.filter(n=>n.endsWith('.xml')).map(n=>zip.file(n).async('string')));return text.join('\n');}
test('server-generated operational PowerPoints are valid branded OOXML',async()=>{const plan={company:'Acme',title:'Joint Project Plan',target_close_date:'2026-12-01',groups:[{id:'g1',name:'Validate'}],milestones:[{groupId:'g1',title:'Validate value case',owner:'joint',dueDate:'2026-10-01',status:'in_progress'}]};const customer=await validOffice(await buildJppPptx(plan,{audience:'customer'}),'ppt'),internal=await validOffice(await buildStakeholderPptx({company:'Acme',stakeholders:[{name:'Pat Lee',title:'CFO',role:'economic_buyer',influence:5,support:4,engaged:true}]}),'ppt');assert.match(customer,/Confidential and Proprietary/);assert.doesNotMatch(customer,/Internal Use Only/);assert.match(internal,/Internal Use Only/);});
