'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),JSZip=require('jszip');
const {buildCustomerROIReportData}=require('../src/shared/customer-roi-report');
const {buildExecutivePdf}=require('../src/exports/executive-pdf');
const {buildExecutivePptx}=require('../src/exports/executive-pptx');
const {buildExecutiveDocx}=require('../src/exports/executive-docx');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
function source(contractMonths=36){return{scenario:{id:'scenario-1',base_id:'base-1',version:3,customer_id:'customer-1',company:'Acme Distribution',industry:'Wholesale Distribution',solution:'Cloud Inventory Platform',owner_username:'james',data:{currency:'USD',contractMonths,modelVersion:28,users:60,labor:65000,laborWastePct:.12,mLabor:.35,effectiveShrinkBase:900000,mShrinkage:.4,inventory:18000000,carryRate:.22,mCarrying:.3,invTurnsCurrent:3,invTurnsBenchmark:5,revenue:250000000,otifBaseline:91,otifTarget:97,contributionMarginPct:.34,mOtif:.35,invest:175000,otc:225000,discRate:.09,implMonths:4,ramp1:.4,ramp2:.75,ramp3:1,threeWhysAct:'Inventory uncertainty increases operating cost and customer risk.',threeWhysNow:'A modernization program creates a dated decision window.',threeWhysCi:'Cloud Inventory provides governed inventory execution across systems.'}},governance:{evidence:{}},stakeholders:[{name:'Alex Morgan',title:'Chief Operations Officer',role:'economic_buyer',engaged:true}],discovery:[],solutionFit:{data:{opportunity:{products:['CIP'],users:'60',goLive:'Q1 2027'},architecture:{erp:'ERP',integrationMethod:'API'}}},jointProjectPlan:{milestones:[{task:'Validate the value case',owner:'joint',dueDate:'2026-10-15',status:'pending'}]},proposal:null,valueHistory:[]};}
test('v6.8.5 report is canonical, complete, and contract-term aware',()=>{for(const months of [12,24,36,48,60]){const report=buildCustomerROIReportData(source(months));assert.equal(report.contract.months,months);assert.equal(report.years.length,months/12);assert.equal(report.financials.totalBenefit,report.years.at(-1).cumulativeBenefit);assert.equal(report.financials.totalInvestment,report.years.at(-1).cumulativeInvestment);assert.equal(report.financials.netValue,report.years.at(-1).cumulativeNetValue);assert.equal(report.chartData.contractTimeline.length,months/12);assert.equal(report.customer.name,'Acme Distribution');assert.equal(report.story.customerSafety.projection,'customer-safe');}});
test('server-side PDF is a real multi-page branded file with chart and values',()=>{const report=buildCustomerROIReportData(source()),pdf=buildExecutivePdf(report);assert.ok(Buffer.isBuffer(pdf));assert.ok(pdf.length>5000);assert.equal(pdf.subarray(0,8).toString(),'%PDF-1.4');const raw=pdf.toString('binary');assert.match(raw,/Cloud Inventory/);assert.match(raw,/Contract value over time/);assert.match(raw,/Acme Distribution/);assert.match(raw,/Confidential and Proprietary/);assert.match(raw,/\/Count 5/);assert.match(raw,/\/Im1/);});
test('PPTX and DOCX are valid branded OOXML and consume report chart data',async()=>{const report=buildCustomerROIReportData(source()),pptx=await buildExecutivePptx(report),docx=await buildExecutiveDocx(report);for(const [buffer,main] of [[pptx,'ppt/presentation.xml'],[docx,'word/document.xml']]){assert.ok(Buffer.isBuffer(buffer));assert.ok(buffer.length>10000);const zip=await JSZip.loadAsync(buffer),names=Object.keys(zip.files);assert.ok(names.includes('[Content_Types].xml'));assert.ok(names.includes(main));const xml=(await Promise.all(names.filter(n=>n.endsWith('.xml')).map(n=>zip.file(n).async('string')))).join('\n');assert.match(xml,/Acme Distribution/);assert.match(xml,/Confidential and Proprietary/);assert.match(xml,/Contract Value Over Time|Contract value by year/);}const pptZip=await JSZip.loadAsync(pptx);assert.ok(Object.keys(pptZip.files).some(name=>name.startsWith('ppt/charts/chart')),'PowerPoint must contain an editable native chart');});
test('authenticated export endpoints use latest saved scenario source and object authorization',()=>{const routes=read('src/routes/scenarios.js'),ui=read('public/executive-output-adapters.js');assert.match(routes,/router\.use\(requireAuth\)/);assert.match(routes,/scenarioAccess\(user,id,'view'\)/);assert.match(routes,/buildCustomerROIReportData\(source\)/);assert.match(routes,/router\.get\('\/:id\/export-pdf'/);assert.match(routes,/router\.get\('\/:id\/export-docx'/);assert.match(routes,/Cache-Control','private, no-store'/);assert.match(ui,/credentials:'same-origin'/);assert.doesNotMatch(ui,/print\.html\?autoprint=1/);});
test('customer loading and deployment recovery remain production-relative',()=>{const switcher=read('public/customer-switcher.js'),render=read('render.yaml'),ignore=read('.gitignore');assert.match(switcher,/fetch\('\/api\/customers'/);assert.match(switcher,/credentials:'same-origin'/);assert.match(switcher,/AbortController/);assert.match(switcher,/Customers could not be loaded/);assert.doesNotMatch(switcher,/localhost|127\.0\.0\.1/);assert.match(render,/npm ci --omit=dev --no-audit --no-fund/);assert.match(render,/healthCheckPath: \/health/);assert.match(ignore,/exports\//);assert.match(ignore,/\*\.pdf/);});
test('login bootstrap does not reference deferred admin cleanup code before it loads',()=>{const index=read('public/index.html'),admin=read('public/admin-cleanup-v661.js');assert.doesNotMatch(index,/window\.adminCleanupPreview\s*=\s*adminCleanupPreview/);assert.match(admin,/window\.adminCleanupPreview=async/);});
