'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const catalog=require('../config/mep-standard-apps.json'),mep=require('../src/shared/mep-standard-apps'),{readiness}=require('../src/shared/handoff-readiness');
const hashes={JDE:'bc33ba4975191b937f0199a6555de368fe12b9d1d8ee9f7a93247f09c423fc73',EBS:'e9ca0c50a5dd4e66346eed688d73b77638ea8167d83d92ed550a546268166bf0','Oracle Fusion':'c11d64c0db3dc4011cd7226fafc3d4a39c1047e93421e761ee9c4b53eac6dc9e','SAP ECC6':'d568c4e70c19759af4d6da7653f09b062280bafb56091ed06753b2d763464bd9','SAP Hana':'d568c4e70c19759af4d6da7653f09b062280bafb56091ed06753b2d763464bd9'};

test('v6.9.0 preserves protected authorities',()=>{const pkg=require('../package.json'),k=require('../config/application-knowledge.json');assert.equal(pkg.version,'6.9.1');assert.equal(k.applicationVersion,'6.9.1');assert.equal(k.roiModel.version,'2.8');assert.equal(k.roiModel.modelVersion,28);assert.equal(k.brandVersion,'1.0');assert.equal(k.knowledgeVersion,'1.0');assert.equal(require('../config/christie-persona.json').personaVersion,'1.0');});
test('governed MEP catalog metadata, counts and exact ordered names are locked',()=>{assert.equal(mep.validateCatalog(),true);assert.equal(catalog.source,'202608 Standard Apps by ERP.xlsx');assert.equal(catalog.catalogVersion,'2026-08');for(const [erp,expected] of Object.entries(mep.EXPECTED_COUNTS)){assert.equal(catalog.erps[erp].length,expected);assert.equal(crypto.createHash('sha256').update(JSON.stringify(catalog.erps[erp])).digest('hex'),hashes[erp],erp);}for(const name of ['Cycle Count - Non Directed (Blind)','Project Move Order Return','Work Order Process Manufacturing Completions','Location to Location Transfer (SLOC to SLOC)','Quality/Blocked to Unrestricted Transfer'])assert.ok(Object.values(catalog.erps).some(x=>x.includes(name)),name);});
test('catalog has one authenticated server/browser authority and no runtime xlsx parser',()=>{const route=read('src/routes/solution-fit-catalog.js'),server=read('server.js'),ui=read('public/solution-fit.js');assert.match(route,/browserCatalog/);assert.match(route,/requireAuth/);assert.match(server,/\/api\/solution-fit\/catalog/);assert.match(ui,/\/api\/solution-fit\/catalog\/mep-standard-apps/);assert.doesNotMatch(server+route+ui,/xlsx|exceljs/i);});
test('Solution Fit routes distinguish active, missing, removed, permission and explicit creation',()=>{const src=read('src/routes/handoffs.js');assert.match(src,/router\.post\('\/:customerId'/);assert.match(src,/capabilities:\{canView:true,canEdit:editAccess\.ok,canCreate/);assert.match(src,/removedRecoverable/);assert.match(src,/deleted_at IS NULL/);assert.match(src,/SOLUTION_FIT_REMOVED/);assert.match(src,/only an Admin may restore/i);assert.match(src,/rolesOf\(req\.user\)\.includes\('se'\)/);});
test('authorization and customer switcher preserve role scope and state-aware actions',()=>{const auth=read('src/authorization.js'),api=read('src/routes/customer-switcher.js'),ui=read('public/customer-switcher.js');assert.match(auth,/se: \[[^\]]*create_solution_fit/);assert.doesNotMatch(auth,/rep: \[[^\]]*create_solution_fit/);assert.match(auth,/handoffs WHERE customer_id=\$1 AND deleted_at IS NULL/);assert.match(auth,/h\.deleted_at IS NULL/);assert.match(api,/canCreate/);assert.match(ui,/Create Solution Fit/);assert.match(ui,/Open Solution Fit/);assert.match(ui,/Not started/);assert.match(ui,/e\.target\.id==='customerSwitcher'/);assert.match(ui,/e\.key==='Escape'/);});
test('removed Solution Fits cannot affect active manager, readiness, scenario or outcome views',()=>{for(const file of ['src/routes/sales-manager.js','src/shared/stage-readiness-service.js','src/routes/scenarios.js'])assert.match(read(file),/handoffs[^;`]*deleted_at IS NULL/s,file);assert.match(read('src/routes/stage-readiness.js'),/LEFT JOIN handoffs h ON h\.customer_id=s\.customer_id AND h\.deleted_at IS NULL/);});
test('Solution Fit screen has recoverable states and governed scope workflow',()=>{const ui=read('public/solution-fit.js');for(const text of ['Solution Fit could not be loaded.','Retry','Switch Customer','Return to ROI Calculator','You do not have permission to view this Solution Fit.','No Solution Fit has been created','Create Solution Fit','Product → ERP → Applications','Additional products','Add non-standard application','Create Gap','Edit Scope'])assert.ok(ui.includes(text),text);assert.ok(!ui.includes("const PRODUCTS = ['MEP','CIP','CPP','Platform']"));assert.match(ui,/catalogVersion:mepCatalog\.catalogVersion/);assert.match(ui,/scopeHistory/);assert.match(ui,/scope_carried_forward/);});
test('standard catalog rows begin unreviewed and customer validation gates readiness',()=>{const state={solutionScope:{primaryProduct:'MEP'},opportunity:{customer:'Acme',solutionEngineer:'SE',products:['MEP'],locations:'1',users:'5',problem:'x',outcome:'y'},architecture:{erp:'JDE',relationship:'Standalone'},partner:{involved:'No'},processes:[{name:'Cycle Count - Directed',selected:true,demoStatus:'Not reviewed',fit:'Not reviewed',customerValidation:'Not validated'}],gaps:[]};let r=readiness(state);assert.ok(r.miss.some(x=>x.label==='Demo status'));assert.ok(r.miss.some(x=>x.label==='Fit status'));assert.ok(r.miss.some(x=>x.label==='Customer validation'));state.processes[0].demoStatus='Demonstrated';state.processes[0].fit='Full fit';r=readiness(state);assert.ok(r.score<100);state.processes[0].customerValidation='Customer validated';r=readiness(state);assert.equal(r.score,100);});
test('onboarding waits for definitive scenario load, stays on Calculator and persists dismissal',()=>{const app=read('public/app.js'),ux=read('public/ux-enhancements.js');assert.match(app,/_scenarioLoadResolved = false/);assert.match(app,/_scenarioLoadResolved = true/);assert.match(ux,/!window\._scenarioLoadResolved/);assert.match(ux,/pane\.active/);assert.match(ux,/tab-calc/);assert.match(ux,/localStorage\.setItem\(preferenceKey/);assert.match(ux,/e\.key==='Escape'/);assert.doesNotMatch(ux,/typeof savedScenarios === 'undefined'\) \|\| !savedScenarios/);});
test('Solution Fit outputs and Christie context carry governed app scope safely',()=>{const ui=read('public/solution-fit.js'),ctx=read('src/shared/christie-context-source.js');for(const text of ['Primary Product:','Catalog Version:','Customer validation','Non-standard',"CIBrand.audience('customer')","CIBrand.audience('internal')"])assert.ok(ui.includes(text),text);for(const key of ['primaryProduct','catalogVersion','standardApplications','nonStandardApplications','demonstratedApplications','partialOrGapApplications','customerValidatedApplications','criticalUnvalidatedApplications'])assert.ok(ctx.includes(key),key);});
