'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const read=file=>fs.readFileSync(path.join(__dirname,'..',file),'utf8');
const economic=require('../public/economic-availability');
function fixture(){return{meta:{customer:'Acme',solution:'CIP',currency:'GBP',preparedBy:'Pat',generatedAt:'2026-09-06T00:00:00Z'},storyRevision:'story-1',economics:{contractMonths:36,annualBenefit:125000,totalContractBenefit:375000,totalContractInvestment:100000,netEconomicBenefit:275000,contractRoi:275,npv:null,payback:9,maturity:{display:'Customer Data'},customerSupportedValuePct:100,activeDrivers:[],contractYears:[]},threeWhys:{whyChange:{value:'Change',status:'Customer supported'},whyNow:{value:'Now',status:'Customer supported'},whyCloudInventory:{value:'Fit',status:'Cloud Inventory position — reviewed'}},solutionAlignment:{exists:true,products:['CIP']},implementationContext:{modelingMonths:3},customerProof:[],nextSteps:{items:[],message:'To validate'}};}
function executiveRuntime(){const window={CIProposalOutputBuilder:require('../public/proposal-output-builder'),CIEconomicAvailability:economic,CIBrand:{logo:()=>'',audience:a=>a==='internal'?'Cloud Inventory · Internal Use Only':'Cloud Inventory · Confidential and Proprietary'},initializeProposalOutputControls(){}};const context={window,document:{getElementById:()=>null,querySelector:()=>null,createElement:()=>({}),body:{prepend(){}}},Date,Intl,Number,Math,Promise,URL,Blob,setTimeout,clearTimeout,console,showToast(){},showExecutiveValueStoryUnavailable(){}};vm.createContext(context);vm.runInContext(read('public/executive-output-adapters.js'),context);return window;}
function proposalRuntime(){const window={executiveValueStory:fixture(),CIProposalOutputBuilder:require('../public/proposal-output-builder'),CIEconomicAvailability:economic,CIBrand:{logo:()=>'',audience:a=>a==='internal'?'Cloud Inventory · Internal Use Only':'Cloud Inventory · Confidential and Proprietary'},initializeProposalOutputControls(){}};const context={window,document:{getElementById:()=>null,querySelector:()=>null,createElement:()=>({}),body:{prepend(){}}},Date,Intl,Number,Math,Promise,setTimeout,clearTimeout,console,showToast(){}};vm.createContext(context);vm.runInContext(read('public/proposal.js'),context);return window;}
test('actual Executive Web renderer embeds governed Ready Review and Draft classification',()=>{const w=executiveRuntime(),s=fixture(),ready=w.renderExecutiveStoryDocument(s,{audience:'customer'}),review=w.renderExecutiveStoryDocument(s,{audience:'customer',draft:true}),draft=w.renderExecutiveStoryDocument(s,{audience:'internal',draft:true});assert.match(ready,/Confidential and Proprietary/);assert.doesNotMatch(ready,/Internal Use Only|REVIEW BEFORE SHARING/);assert.match(review,/REVIEW BEFORE SHARING/);assert.match(review,/Confidential and Proprietary/);assert.match(draft,/CONFIDENTIAL — INTERNAL USE ONLY/);assert.match(draft,/DRAFT — NOT READY FOR CUSTOMER SHARING/);assert.match(draft,/Internal Use Only/);assert.doesNotMatch(draft,/Confidential and Proprietary/);});
test('Executive Web loads story and readiness together and fails closed',()=>{const source=read('public/executive-output-adapters.js');assert.match(source,/Promise\.all\(\[window\.loadExecutiveValueStory\(true\),window\.getExecutiveOutputReadiness\('executive_view'\)\]\)/);assert.match(source,/Executive Value Story loading…/);assert.match(source,/executive_web\.failed_closed/);});
test('actual Proposal Preview renderer follows readiness and excludes internal commercial notes',()=>{const w=proposalRuntime(),draft={title:'Plan',situation:'Situation',recommendation:'Proceed',commercialTerms:'Total investment: £150,000'},ready=w.renderProposalPreviewForReadiness(draft,{status:'ready'}),review=w.renderProposalPreviewForReadiness(draft,{status:'review'}),internal=w.renderProposalPreviewForReadiness(draft,{status:'draft_only'});assert.equal(ready.label,'Customer-facing preview');assert.equal(ready.audience,'customer');assert.match(ready.html,/Confidential and Proprietary/);assert.doesNotMatch(ready.html,/150,000/);assert.match(review.html,/REVIEW BEFORE SHARING/);assert.match(review.html,/Confidential and Proprietary/);assert.equal(internal.label,'Internal Draft Preview');assert.equal(internal.audience,'internal');assert.match(internal.html,/CONFIDENTIAL — INTERNAL USE ONLY/);assert.match(internal.html,/DRAFT — NOT READY FOR CUSTOMER SHARING/);assert.match(internal.html,/Internal Use Only/);assert.doesNotMatch(internal.html,/Confidential and Proprietary|150,000/);});
