'use strict';
const {describe,test,before,after}=require('node:test'),assert=require('node:assert/strict');
const HAS_DB=!!process.env.DATABASE_URL,blocked=HAS_DB?false:'DATABASE_URL unavailable — v6.9.30 PostgreSQL value-application integration is NOT TESTED';
const USER=process.env.TEST_ADMIN_USER||'admin',PASS=process.env.ADMIN_PASSWORD||process.env.TEST_ADMIN_PASS||'CloudInventory2026!';
let server,base,token,db,scenario,linkToken,sessionId,question,submissionId;
async function api(path,{method='GET',auth=token,body}={}){const headers={'Content-Type':'application/json'};if(auth)headers.Authorization='Bearer '+auth;const response=await fetch(base+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});return{status:response.status,json:await response.json().catch(()=>null)};}
if(!HAS_DB)test('v6.9.30 transactional Prospect value application PostgreSQL gate',{skip:blocked},()=>{});
else describe('v6.9.30 transactional Prospect value application',{concurrency:false},()=>{
  before(async()=>{process.env.NODE_ENV='test';const{runMigrations}=require('../src/migrate');await runMigrations();db=require('../src/db');const{app}=require('../server');server=await new Promise(resolve=>{const listener=app.listen(0,'127.0.0.1',()=>resolve(listener));});base='http://127.0.0.1:'+server.address().port;const login=await api('/api/auth/login',{method:'POST',auth:null,body:{username:USER,password:PASS}});assert.equal(login.status,200);token=login.json.token;const label='v6930 '+Date.now();const made=await api('/api/scenarios',{method:'POST',body:{name:label,company:label,data:{name:label,company:label,industry:'manufacturing',modelVersion:28,annualWriteOff:100000,invest:10000,contractMonths:36}}});assert.equal(made.status,201);scenario=made.json.scenario||made.json;const link=await api('/api/discovery/sessions',{method:'POST',body:{scenarioId:scenario.id}});assert.equal(link.status,200);linkToken=link.json.token;sessionId=link.json.sessionId;const publicView=await api('/api/discovery/sessions/'+linkToken,{auth:null});assert.equal(publicView.status,200);const financial=(await db.query("SELECT question_id,canonical_input FROM discovery_session_questions WHERE discovery_session_id=$1 AND classification='financial_input' ORDER BY display_order LIMIT 1",[sessionId])).rows[0];assert.ok(financial);question=publicView.json.questionnaire.flatMap(section=>section.questions).find(item=>item.id===financial.question_id);assert.ok(question);await api('/api/discovery/sessions/'+linkToken+'/answers',{method:'PUT',auth:null,body:{questionId:question.id,answer:'.5'}});const submitted=await api('/api/discovery/sessions/'+linkToken+'/submit',{method:'POST',auth:null,body:{clientSubmissionId:'v6930-'+Date.now()}});assert.equal(submitted.status,201);submissionId=submitted.json.submissionId;});
  after(async()=>{if(server)await new Promise(resolve=>server.close(resolve));});
  test('review, apply, idempotent replay, reload, application row and audit agree',async()=>{const outbox=await db.query('SELECT * FROM prospect_submission_notifications WHERE submission_id=$1',[submissionId]);assert.equal(outbox.rowCount,1);const submissionAudit=await db.query("SELECT * FROM audit_log WHERE action='discovery.submission_snapshot_created' AND entity_id=$1",[submissionId]);assert.equal(submissionAudit.rowCount,1);const before=await api('/api/scenarios/'+scenario.id+'/prospect-evidence-review');assert.equal(before.status,200);const row=before.json.rows.find(item=>item.event);assert.ok(row);assert.equal(row.status,'AVAILABLE');const body={eventId:row.event.id,idempotencyKey:'v6930-apply-once'};const applied=await api('/api/scenarios/'+scenario.id+'/value-history/'+encodeURIComponent(row.canonicalInput)+'/apply',{method:'POST',body});assert.equal(applied.status,201);assert.equal(applied.json.apply.persisted,true);assert.equal(String(applied.json.apply.provenance.discoverySubmissionId),String(submissionId));const replay=await api('/api/scenarios/'+scenario.id+'/value-history/'+encodeURIComponent(row.canonicalInput)+'/apply',{method:'POST',body});assert.equal(replay.status,200);assert.equal(replay.json.alreadyApplied,true);const afterReview=await api('/api/scenarios/'+scenario.id+'/prospect-evidence-review');assert.equal(afterReview.status,200);assert.equal(afterReview.json.rows.find(item=>item.canonicalInput===row.canonicalInput).status,'APPLIED');const saved=(await db.query('SELECT data FROM scenarios WHERE id=$1',[scenario.id])).rows[0].data;assert.equal(saved.fieldStates[row.canonicalInput],'confirmed_prospect');assert.equal(String(saved.fieldProvenance[row.canonicalInput].eventId),String(row.event.id));const apps=await db.query('SELECT * FROM roi_value_applications WHERE target_scenario_id=$1 AND source_value_event_id=$2',[scenario.id,row.event.id]);assert.equal(apps.rowCount,1);const audits=await db.query("SELECT * FROM audit_log WHERE action='roi_value.applied' AND entity_id=$1",[apps.rows[0].id]);assert.equal(audits.rowCount,1);});
  test('application rows are immutable',async()=>{const row=(await db.query('SELECT id FROM roi_value_applications WHERE target_scenario_id=$1 LIMIT 1',[scenario.id])).rows[0];await assert.rejects(db.query("UPDATE roi_value_applications SET canonical_input='tampered' WHERE id=$1",[row.id]),/immutable/i);});
});
