'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8'),exists=f=>fs.existsSync(path.join(root,f));
test('verified release lineage is machine-readable and version-neutral governance is retained',()=>{const x=JSON.parse(read('release-lineage.json'));assert.equal(x.applicationVersion,'6.9.26');assert.equal(x.parentVersion,'6.9.25');assert.equal(x.parentSha256,'e946d2170675053022d68acfba16205829387b7e304a0da28eadeb8959c09113');assert.equal(x.parentCommit,'2ea230462afce1ee6b53ee29805ccbac89aacbe6');assert.equal(x.developerSourceSnapshot,'77befba6d01e1d68c5ab989830fa2a70a6b20d8f');assert.doesNotMatch(read('BUILD_GOVERNANCE_CONTRACT.md'),/ONLY authorized source package[\s\S]{0,120}v\d+\.\d+\.\d+/i);});
test('v6.9.4 Solution Fit cross-account scope and behavioral governance survive recovery',()=>{for(const f of ['migrations/036_solution_fit_cross_account.sql','src/routes/solution-fit-customers.js','public/solution-fit-picker.js','test/solution-fit-authorization-behavior.test.js','test/solution-fit-picker-behavior.test.js','test/v692-se-solution-fit-access.test.js'])assert.equal(exists(f),true,f);assert.match(read('migrations/036_solution_fit_cross_account.sql'),/solution_fit_cross_account/);});
test('Executive output and narrative governance survive recovery',()=>{assert.equal(exists('scripts/production-output-dependencies.js'),true);const narrative=read('public/narrative.js'),audit=read('scripts/audit-active-output-paths.js');assert.doesNotMatch(narrative,/THREE_WHYS_LIBRARY/);assert.doesNotMatch(read('public/app.js'),/function renderExec\s*\(/);assert.match(audit,/production-output-dependencies/);assert.doesNotMatch(read('src/shared/executive-value-story.js'),/annualBenefit\s*\/\s*12|0\.7\s*\*|1\.3\s*\*/);});
test('permanent test registry is present and includes Rep Confirmed',()=>{const x=JSON.parse(read('config/permanent-release-tests.json'));assert.ok(x.tests.length>=14);assert.ok(x.tests.some(t=>t.invariant==='Rep Confirmed provenance'));for(const t of x.tests)assert.equal(exists(t.path),true,t.path);});
test('browser narrative claims are server-normalized and immutable Prospect submission is authoritative',()=>{const route=read('src/routes/scenarios.js');assert.match(route,/normalizeNarrativeMeta/);assert.match(route,/discovery_submissions s JOIN discovery_submission_answers/);assert.match(route,/requested\.source==='ai_draft'/);assert.doesNotMatch(route,/requested\.source==='customer_validated'/);});
test('narrative normalization behavior rejects forged customer validation and recognizes an exact submitted answer',()=>{const normalize=require('../src/routes/scenarios').normalizeNarrativeMeta,narrative={threeWhysAct:'Submitted fact',threeWhysCi:'Vendor positioning',threeWhysNow:'Rep deadline'};const meta=normalize(narrative,{whyChange:{source:'customer_validated'},whyCloudInventory:{source:'customer_validated'},whyNow:{source:'customer_validated'}},[{question_id:'ve5',answer_text:'Submitted fact'}]);assert.equal(meta.whyChange.source,'customer_discovery');assert.equal(meta.whyCloudInventory.source,'rep_authored');assert.equal(meta.whyNow.source,'rep_authored');});
