'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const {buildProspectPreview}=require('../src/shared/prospect-roi-preview');
const {buildExecutiveValueStory}=require('../src/shared/executive-value-story');
const {savedScenarioCurrency}=require('../src/shared/value-history');
const registry=require('../src/shared/output-registry'),dependencies=require('../scripts/production-output-dependencies');
test('Prospect preview is server calculated, customer safe, has no arbitrary range, and withholds ROI/payback without investment',()=>{
 const result=buildProspectPreview({industry:'distribution',currency:'GBP',questions:[{question_id:'q1',canonical_input:'inventoryValue',unit:'currency'}],answers:[{question_id:'q1',answer:'1000000'}],scenarioData:{}});
 assert.equal(result.currency,'GBP');assert.equal(result.modelVersion,28);assert.ok(result.modeledAnnualBenefit>0);assert.equal(result.investmentDefined,false);assert.equal(result.roi,null);assert.equal(result.payback,null);assert.deepEqual(Object.keys(result).sort(),['activeDrivers','currency','driverEvidenceState','investmentDefined','modelVersion','modeledAnnualBenefit','payback','previewDisclaimer','roi'].sort());
 const browser=read('public/prospect.html');assert.doesNotMatch(browser,/calcROI\s*\(|\*\s*0?\.7\b|70%[–-]100%|Per month without Cloud Inventory|recoverable value foregone/);assert.match(read('server.js'),/sessions\/:token\/roi-preview/);
});
test('customer email requires a saved story, enforces readiness, and has no browser economic or messaging bypass',()=>{const src=read('public/features.js'),section=src.slice(src.indexOf('async function generateEmail'),src.indexOf('function copyEmail'));assert.match(section,/Save the scenario before creating customer-facing value messaging/);assert.match(section,/executive-value-story/);assert.match(section,/executive-output-readiness/);assert.match(section,/draft_only/);assert.match(section,/acknowledge/);assert.match(section,/CustomerEmail\.buildCustomerEmail/);assert.match(section,/CustomerEmail\.mergePersonalization/);assert.doesNotMatch(section,/calcROI\s*\(|getVals\s*\(|under 12 months|30-minute technical discovery|live demo focused|attached a full executive presentation|a Nextworld Company/);});
test('Champion Kit is inactive and Executive PowerPoint has no unsaved local fallback',()=>{assert.equal(registry.getOutput('deal-coach-champion-kit').active,false);assert.match(read('public/deal-coach.js'),/Champion Kit — unavailable/);assert.doesNotMatch(read('public/pptx-export.js'),/pptLocalContext|calcROI\s*\(|exportToPowerPoint/);const adapter=read('public/executive-output-adapters.js');assert.match(adapter,/Save the scenario before creating an Executive PowerPoint/);assert.doesNotMatch(adapter,/_forceExecutiveDraft|corePpt/);assert.match(adapter,/internalDraft/);});
test('every active customer surface owner exists and is in the production dependency registry',()=>{for(const output of registry.OUTPUTS.filter(x=>x.active&&x.audience==='customer')){assert.ok(fs.existsSync(path.join(root,output.ownerModule)),output.outputId);assert.ok(dependencies.includes(output.ownerModule),output.outputId);assert.equal(output.customerSafe,true);}assert.equal(registry.validateRegistry(),true);});
test('customer Discovery Three Why requires an exact immutable evidence reference',()=>{const scenario={id:'s1',base_id:'b1',version:3,company:'Acme',data:{modelVersion:28,threeWhysAct:'Customer fact',threeWhysMeta:{whyChange:{source:'customer_discovery',validationStatus:'Customer supported',discoverySubmissionId:'sub1',submissionNumber:2,questionId:'ve5',submittedAt:'2026-09-05T12:00:00.000Z',sourceScenarioId:'s1',sourceScenarioVersion:3}}}};const evidence=[{question_id:'ve5',answer:'Customer fact',entered_by:'prospect_submission',submission_id:'sub1',submission_number:2,submitted_at:'2026-09-05T12:00:00.000Z',source_scenario_id:'s1',source_scenario_version:3,is_latest:true}];const valid=buildExecutiveValueStory({scenario,discovery:evidence});assert.equal(valid.threeWhys.whyChange.status,'Customer supported');const tampered=buildExecutiveValueStory({scenario,discovery:[{...evidence[0],answer:'Different fact'}]});assert.equal(tampered.threeWhys.whyChange.status,'Needs validation');});
test('Rep Confirmed currency is owned by the saved scenario',()=>{assert.equal(savedScenarioCurrency({currency:'GBP'},'USD'),'GBP');assert.equal(savedScenarioCurrency({currency:'INVALID'},'GBP'),'USD');const route=read('src/routes/scenarios.js');const section=route.slice(route.indexOf("router.post('/:id/value-history/:canonicalInput/rep-confirm'"),route.indexOf("router.post('/:id/value-history/:canonicalInput/apply'"));assert.match(section,/savedScenarioCurrency\(sc\.data\)/);assert.doesNotMatch(section,/b\.currency/);});
