'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const {evaluateExecutiveOutputReadiness,OUTPUTS}=require('../src/shared/executive-output-readiness');
const email=require('../public/customer-email'),currency=require('../public/native-currency'),registry=require('../src/shared/output-registry');
function story(){return{meta:{scenarioId:'s1',customer:'Acme',currency:'USD',preparedBy:'Pat'},storyRevision:'r1',threeWhys:{whyChange:{value:'Reduce count effort',status:'Customer supported',source:'customer_validated'},whyNow:{value:'Opening a site',status:'Customer supported',source:'customer_validated'},whyCloudInventory:{value:'Mobile alignment',status:'Cloud Inventory position — reviewed',source:'rep_authored'}},economics:{annualBenefit:100,totalContractBenefit:300,totalContractInvestment:50,netEconomicBenefit:250,contractRoi:500,npv:220,payback:6,maturity:{level:2,display:'Customer-Data Value Case'},customerSupportedValuePct:100,activeDrivers:[{label:'Labour',annualValue:100,status:'Customer supported',customerSupported:true}]},solutionAlignment:{exists:true},implementationContext:{modelingMonths:0},nextSteps:{items:[{milestone:'Validate baseline',owner:'Joint',dueDate:'2026-09-30'}]},unavailableProofIds:[]};}
test('customer_email is a supported readiness type with ready, review, draft, and reject behavior',()=>{const s=story();assert.ok(OUTPUTS.has('customer_email'));assert.equal(evaluateExecutiveOutputReadiness(s,{outputType:'customer_email'}).status,'ready');const review=story();review.nextSteps.items=[];assert.equal(evaluateExecutiveOutputReadiness(review,{outputType:'customer_email'}).status,'review');const draft=story();draft.threeWhys.whyNow={value:'To validate',status:'To validate'};assert.equal(evaluateExecutiveOutputReadiness(draft,{outputType:'customer_email'}).status,'draft_only');assert.throws(()=>evaluateExecutiveOutputReadiness(s,{outputType:'unknown'}),/Unsupported/);});
test('email distinguishes unavailable ROI, payback not achieved, and legitimate zero',()=>{const s=story();s.economics.contractRoi=null;s.economics.payback=null;const missing=email.buildCustomerEmail(s);assert.match(missing.body,/Contract ROI: Not yet established/);assert.match(missing.body,/Payback: Payback not achieved within contract term/);s.economics.totalContractInvestment=null;const unestablished=email.buildCustomerEmail(s);assert.match(unestablished.body,/Payback: Payback not yet established/);s.economics.totalContractInvestment=50;s.economics.contractRoi=0;s.economics.payback=0;const zero=email.buildCustomerEmail(s);assert.match(zero.body,/Contract ROI: 0%/);assert.match(zero.body,/Payback: 0\.0 months/);});
test('AI personalization cannot alter locked facts, Three Whys, economics, drivers, or joint steps',()=>{const original=email.buildCustomerEmail(story()),merged=email.mergePersonalization(original,{intro:'Friendly opening claiming $9 million in annual benefit',closing:'Supportive close with Contract ROI 9999%'});assert.equal(merged.locked,original.locked);assert.match(merged.body,/Reduce count effort/);assert.match(merged.body,/Contract ROI: 500%/);assert.match(merged.body,/Validate baseline/);assert.doesNotMatch(merged.body,/9 million|9999%/);});
test('native Prospect currency renders without FX conversion',()=>{const amount=1250000;assert.match(currency.formatCompactCurrency(amount,'USD'),/^\$/);assert.match(currency.formatCompactCurrency(amount,'GBP'),/^£/);assert.match(currency.formatCompactCurrency(amount,'EUR'),/^€/);assert.match(currency.formatCompactCurrency(amount,'AUD'),/^A\$/);assert.match(currency.formatCompactCurrency(amount,'NZD'),/^NZ\$/);for(const code of currency.SUPPORTED)assert.match(currency.formatCompactCurrency(amount,code),/1\.3M/);});
test('browser helper fails closed until the sole authoritative Executive PowerPoint adapter loads',()=>{const button={disabled:false,setAttribute(k,v){this[k]=v;}},document={getElementById:id=>id==='pptxExportBtn'?button:null,createElement(){throw new Error('no dependency should load');},head:{appendChild(){throw new Error('no dependency should load');}}},window={CIBrand:{officeTheme:()=>({H:5.625,GRAY_TXT:'777',FONT:'Arial',ORANGE:'f80',GRAY_BG:'fff',LOGO:'x',LOGO_W:1,LOGO_H:1,NAVY:'000',CYAN:'0aa'}),audience:()=>''}};vm.runInNewContext(read('public/pptx-export.js'),{window,document,Promise,Number,Math,showToast(){}});assert.equal(button.disabled,true);assert.equal(window.exportToPowerPoint,undefined);const adapter=read('public/executive-output-adapters.js');assert.equal((adapter.match(/window\.exportToPowerPoint\s*=/g)||[]).length,1);assert.doesNotMatch(read('src/routes/scenarios.js'),/pptx-context/);});
test('registry mappings and inactive Champion Kit UI are explicit',()=>{assert.equal(registry.validateRegistry(),true);for(const output of registry.OUTPUTS.filter(x=>x.active)){if(output.readinessRequired)assert.ok(OUTPUTS.has(output.readinessOutputType),output.outputId);else assert.ok(output.readinessNotApplicable,output.outputId);}assert.equal(registry.getOutput('deal-coach-champion-kit').active,false);const coach=read('public/deal-coach.js');assert.match(coach,/Champion Kit — unavailable/);assert.match(coach,/disabled aria-disabled="true"/);});
