const express=require('express');
const {query,transaction}=require('../db');
const {requireAuth}=require('../middleware/auth');
const {hasPermission,getUserTeams,effectivePermissions,customerAccess,solutionFitAccess,getAuthorizedSalesReps,getTeamUsers,listAuthorizedSolutionFits}=require('../authorization');
const {log,ACTIONS}=require('../audit');
const router=express.Router();router.use(requireAuth);
const deny=(res)=>res.status(403).json({error:'Sales Team administration permission required.'});
const admin=req=>hasPermission(req.user,'manage_sales_teams');

router.get('/me',async(req,res)=>{try{res.json({roles:req.user.roleKeys,permissions:effectivePermissions(req.user),teams:await getUserTeams(req.user.id)});}catch(e){res.status(500).json({error:'Failed to load access profile.'});}});
router.get('/me/reps',async(req,res)=>{try{res.json(await getAuthorizedSalesReps(req.user));}catch(e){res.status(500).json({error:'Failed to load authorized reps.'});}});
router.get('/me/solution-engineers',async(req,res)=>{try{res.json(await getTeamUsers(req.user.id,'se'));}catch(e){res.status(500).json({error:'Failed to load team Sales Engineers.'});}});
router.get('/me/sales-leaders',async(req,res)=>{try{res.json(await getTeamUsers(req.user.id,'sales_manager'));}catch(e){res.status(500).json({error:'Failed to load team Sales Leaders.'});}});
router.get('/me/solution-fits',async(req,res)=>{try{res.json(await listAuthorizedSolutionFits(req.user));}catch(e){res.status(500).json({error:'Failed to load authorized Solution Fits.'});}});
router.get('/users',async(req,res)=>{if(!admin(req))return deny(res);try{const {rows}=await query(`SELECT u.id,u.username,u.email,u.role,u.roles,u.is_active,COALESCE((SELECT ARRAY_AGG(t.name ORDER BY t.name) FROM sales_team_memberships m JOIN sales_teams t ON t.id=m.team_id WHERE m.user_id=u.id AND m.is_active=TRUE),'{}') team_names FROM users u ORDER BY u.username`);res.json(rows);}catch(e){res.status(500).json({error:'Failed to load users.'});}});
router.get('/',async(req,res)=>{try{const all=admin(req);const {rows}=await query(`SELECT t.id,t.name,t.status,t.primary_leader_id,pl.username primary_leader,t.created_at,t.updated_at,
 COUNT(DISTINCT m.user_id)::int member_count,
 COUNT(DISTINCT m.user_id) FILTER(WHERE 'rep'=ANY(m.membership_functions))::int rep_count,
 COUNT(DISTINCT m.user_id) FILTER(WHERE 'se'=ANY(m.membership_functions))::int se_count,
 COUNT(DISTINCT m.user_id) FILTER(WHERE m.user_id=t.primary_leader_id OR 'sales_manager'=ANY(m.membership_functions))::int leader_count,
 COUNT(DISTINCT m.user_id) FILTER(WHERE m.user_id<>t.primary_leader_id AND 'sales_manager'=ANY(m.membership_functions))::int additional_leader_count,
 (SELECT COUNT(*)::int FROM customers c JOIN sales_team_memberships cm ON cm.user_id=c.owner_id AND cm.team_id=t.id AND cm.is_active=TRUE WHERE c.deleted_at IS NULL) customer_count,
 (SELECT COUNT(*)::int FROM handoffs h JOIN customers c ON c.id=h.customer_id JOIN sales_team_memberships hm ON hm.user_id=c.owner_id AND hm.team_id=t.id AND hm.is_active=TRUE WHERE h.deleted_at IS NULL AND c.deleted_at IS NULL) solution_fit_count
 FROM sales_teams t LEFT JOIN users pl ON pl.id=t.primary_leader_id LEFT JOIN sales_team_memberships m ON m.team_id=t.id AND m.is_active=TRUE
 WHERE ($2 OR EXISTS(SELECT 1 FROM sales_team_memberships mine WHERE mine.team_id=t.id AND mine.user_id=$1 AND mine.is_active=TRUE))
 GROUP BY t.id,pl.username ORDER BY t.name`,[req.user.id,all]);res.json(rows);}catch(e){console.error(e);res.status(500).json({error:'Failed to load Sales Teams.'});}});
router.get('/:id',async(req,res)=>{try{const all=admin(req);const {rows}=await query(`SELECT t.*,pl.username primary_leader FROM sales_teams t LEFT JOIN users pl ON pl.id=t.primary_leader_id WHERE t.id=$1 AND ($3 OR EXISTS(SELECT 1 FROM sales_team_memberships m WHERE m.team_id=t.id AND m.user_id=$2 AND m.is_active=TRUE))`,[req.params.id,req.user.id,all]);if(!rows.length)return res.status(404).json({error:'Sales Team not found.'});const members=await query(`SELECT m.id,m.user_id,u.username,u.email,u.roles,u.role,u.is_active,m.membership_functions,m.effective_start,m.effective_end,m.is_active FROM sales_team_memberships m JOIN users u ON u.id=m.user_id WHERE m.team_id=$1 ORDER BY u.username`,[req.params.id]);const eligibilityWarnings=members.rows.filter(m=>m.is_active).flatMap(m=>membershipWarnings(m));res.json({...rows[0],members:members.rows,eligibility_warnings:eligibilityWarnings});}catch(e){res.status(500).json({error:'Failed to load Sales Team.'});}});
router.post('/',async(req,res)=>{if(!admin(req))return deny(res);const b=req.body||{};if(!String(b.name||'').trim())return res.status(400).json({error:'Team name is required.'});try{await validatePrimaryLeader(b.primaryLeaderId);const normalized=await validateMembers(membersWithLeader(b));const {rows}=await query(`INSERT INTO sales_teams(name,status,primary_leader_id,created_by,updated_by) VALUES($1,$2,$3,$4,$4) RETURNING *`,[b.name.trim(),b.status==='inactive'?'inactive':'active',b.primaryLeaderId||null,req.user.id]);await syncMembers(rows[0].id,normalized,req.user.id);await log({userId:req.user.id,action:ACTIONS.SALES_TEAM_CREATED,entityType:'sales_team',entityId:rows[0].id,detail:{name:b.name,status:rows[0].status,primaryLeaderId:b.primaryLeaderId||null,members:normalized},ipAddress:req.ip});await auditMembershipChanges(rows[0].id,[],normalized,req);res.status(201).json(rows[0]);}catch(e){res.status(e.code==='23505'?409:400).json({error:e.code==='23505'?'Team name already exists.':e.message||'Failed to create Sales Team.'});}});
router.put('/:id',async(req,res)=>{if(!admin(req))return deny(res);const b=req.body||{};try{const before=await query('SELECT * FROM sales_teams WHERE id=$1',[req.params.id]);if(!before.rows.length)return res.status(404).json({error:'Sales Team not found.'});if(before.rows[0].status==='active'&&b.status==='inactive'&&!b.confirmDeactivate)return res.status(409).json({error:'Confirm team deactivation. Team-derived access will stop while historical records remain intact.',code:'CONFIRM_DEACTIVATE'});const beforeMembers=await query(`SELECT user_id,membership_functions FROM sales_team_memberships WHERE team_id=$1 AND is_active=TRUE`,[req.params.id]);const normalized=Array.isArray(b.members)?await validateMembers(membersWithLeader(b)):null;await transaction(async c=>{await validatePrimaryLeader(b.primaryLeaderId,c.query.bind(c));await c.query(`UPDATE sales_teams SET name=COALESCE($1,name),status=COALESCE($2,status),primary_leader_id=$3,updated_by=$4,updated_at=NOW() WHERE id=$5`,[b.name?.trim()||null,b.status||null,b.primaryLeaderId||null,req.user.id,req.params.id]);if(normalized)await syncMembers(req.params.id,normalized,req.user.id,c.query.bind(c));});await log({userId:req.user.id,action:ACTIONS.SALES_TEAM_UPDATED,entityType:'sales_team',entityId:req.params.id,detail:{before:before.rows[0],after:{...b,members:normalized||undefined}},ipAddress:req.ip});if(b.status&&b.status!==before.rows[0].status)await log({userId:req.user.id,action:b.status==='active'?'sales_team.activated':'sales_team.deactivated',entityType:'sales_team',entityId:req.params.id,detail:{previousStatus:before.rows[0].status,newStatus:b.status},ipAddress:req.ip});if(normalized)await auditMembershipChanges(req.params.id,beforeMembers.rows,normalized,req);res.json({ok:true});}catch(e){console.error(e);res.status(400).json({error:e.message||'Failed to update Sales Team.'});}});
router.get('/diagnostics/customer/:customerId',async(req,res)=>{if(!admin(req))return deny(res);const userId=req.query.userId||req.user.id;try{const u=await query('SELECT id,role,roles FROM users WHERE id=$1',[userId]);if(!u.rows.length)return res.status(404).json({error:'User not found.'});const user={id:u.rows[0].id,role:u.rows[0].role,roleKeys:u.rows[0].roles};res.json({customer:await customerAccess(user,req.params.customerId,'view'),solutionFit:await solutionFitAccess(user,req.params.customerId,'view'),roles:user.roleKeys,permissions:effectivePermissions(user)});}catch(e){res.status(500).json({error:'Failed to explain access.'});}});

function membersWithLeader(b){const list=Array.isArray(b.members)?b.members.slice():[];if(b.primaryLeaderId)list.push({userId:b.primaryLeaderId,functions:['sales_manager']});return list;}
async function validatePrimaryLeader(userId,runner=query){if(!userId)return;const {rows}=await runner(`SELECT id FROM users WHERE id=$1 AND is_active=TRUE AND (role='sales_manager' OR 'sales_manager'=ANY(roles))`,[userId]);if(!rows.length)throw new Error('Primary Sales Leader must be an active user with the Sales Leader role.');}
const FUNCTION_ROLE={rep:'rep',se:'se',sales_manager:'sales_manager'};
const MEMBERSHIP_AUDIT={sales_manager:{added:'sales_team.leader_added',removed:'sales_team.leader_removed'},rep:{added:'sales_team.rep_added',removed:'sales_team.rep_removed'},se:{added:'sales_team.se_added',removed:'sales_team.se_removed'}};
function userRoles(u){return new Set([...(u.roles||[]),u.role].filter(Boolean));}
function membershipWarnings(m){const held=userRoles(m);return(m.membership_functions||[]).filter(fn=>FUNCTION_ROLE[fn]&&!held.has(FUNCTION_ROLE[fn])).map(fn=>({userId:m.user_id,username:m.username,function:fn,message:`${m.username} is assigned as ${fn==='se'?'a Sales Engineer':fn==='rep'?'a Sales Rep':'a Sales Leader'} but no longer has that role.`}));}
function normalizeMembers(members){const byUser=new Map();for(const m of members||[]){if(!m||!m.userId)continue;const id=String(m.userId),prior=byUser.get(id)||{userId:m.userId,functions:[],effectiveStart:m.effectiveStart||null};prior.functions=[...new Set([...prior.functions,...(m.functions||[]).filter(fn=>FUNCTION_ROLE[fn])])];byUser.set(id,prior);}return[...byUser.values()];}
async function validateMembers(members,runner=query){const normalized=normalizeMembers(members);if(!normalized.length)return normalized;const check=await runner(`SELECT id,username,role,roles,is_active FROM users WHERE id=ANY($1::uuid[])`,[normalized.map(x=>x.userId)]);if(check.rows.length!==normalized.length)throw new Error('One or more users do not exist.');const byId=new Map(check.rows.map(u=>[String(u.id),u]));for(const m of normalized){const u=byId.get(String(m.userId));if(!u.is_active)throw new Error(`${u.username} is inactive and cannot be assigned.`);const held=userRoles(u);for(const fn of m.functions)if(!held.has(FUNCTION_ROLE[fn]))throw new Error(`${u.username} must first receive the ${fn==='se'?'Sales Engineer':fn==='rep'?'Sales Rep':'Sales Leader'} role in User Management.`);}return normalized;}
async function syncMembers(teamId,members,adminId,runner=query){
  const normalized=normalizeMembers(members);
  const current=await runner('SELECT user_id FROM sales_team_memberships WHERE team_id=$1 AND is_active=TRUE',[teamId]);
  const next=new Set(normalized.map(x=>String(x.userId)));
  for(const old of current.rows)if(!next.has(String(old.user_id)))await runner(`UPDATE sales_team_memberships SET is_active=FALSE,effective_end=CURRENT_DATE,updated_by=$1,updated_at=NOW() WHERE team_id=$2 AND user_id=$3`,[adminId,teamId,old.user_id]);
  for(const m of normalized)await runner(`INSERT INTO sales_team_memberships(team_id,user_id,membership_functions,effective_start,is_active,created_by,updated_by) VALUES($1,$2,$3,COALESCE($4,CURRENT_DATE),TRUE,$5,$5) ON CONFLICT(team_id,user_id) DO UPDATE SET membership_functions=EXCLUDED.membership_functions,effective_start=EXCLUDED.effective_start,effective_end=NULL,is_active=TRUE,updated_by=$5,updated_at=NOW()`,[teamId,m.userId,m.functions||[],m.effectiveStart||null,adminId]);
}
async function auditMembershipChanges(teamId,before,after,req){const oldMap=new Map((before||[]).map(m=>[String(m.user_id||m.userId),new Set(m.membership_functions||m.functions||[])])),newMap=new Map((after||[]).map(m=>[String(m.userId),new Set(m.functions||[])])),ids=new Set([...oldMap.keys(),...newMap.keys()]);for(const userId of ids){const oldFns=oldMap.get(userId)||new Set(),newFns=newMap.get(userId)||new Set();for(const fn of newFns)if(!oldFns.has(fn))await log({userId:req.user.id,action:MEMBERSHIP_AUDIT[fn]?.added||ACTIONS.TEAM_MEMBER_ADDED,entityType:'sales_team',entityId:teamId,detail:{memberUserId:userId,function:fn,previousFunctions:[...oldFns],newFunctions:[...newFns]},ipAddress:req.ip});for(const fn of oldFns)if(!newFns.has(fn))await log({userId:req.user.id,action:MEMBERSHIP_AUDIT[fn]?.removed||ACTIONS.TEAM_MEMBER_REMOVED,entityType:'sales_team',entityId:teamId,detail:{memberUserId:userId,function:fn,previousFunctions:[...oldFns],newFunctions:[...newFns]},ipAddress:req.ip});}}
module.exports=router;
