'use strict';
const brand = require('../../config/cloud-inventory-brand.json');
const strip = value => String(value || '').replace(/^#/, '').toUpperCase();
function logo(role) { const item = brand.logos[role]; if (!item) throw new Error(`Unknown Cloud Inventory logo role: ${role}`); return item.path; }
function audience(kind = 'customer', year = new Date().getFullYear()) { const item = brand.audiences[kind] || brand.audiences.customer; return `© ${year} ${item.label} · ${item.confidentiality}`; }
function documentTheme(kind = 'customer') { const d=brand.document, role=d.logoRole, item=brand.logos[role]; return Object.freeze({ ...Object.fromEntries(Object.entries(d).filter(([,v])=>typeof v==='string').map(([k,v])=>[k,strip(v)])), font:brand.typography.officePrimary,fontFallback:brand.typography.officeFallback,fontSecondaryFallback:brand.typography.officeSecondaryFallback,type:brand.typography.scale.officeHalfPoints,logoRole:role,logo:logo(role),logoAspect:item.intrinsicHeight/item.intrinsicWidth,footer:audience(kind) }); }
function officeTheme() { const c = brand.colors.core,n=brand.colors.neutral,s=brand.colors.semantic,d=documentTheme('customer'),item=brand.logos.logoOfficeHighResolution; return Object.freeze({ W:10,H:5.625,NAVY:strip(c.dark),CYAN:strip(c.blue),CYAN_DARK:strip(c.blueDark),ORANGE:strip(c.orangeDark),RED:strip(c.deepRed),GRAY_BG:strip(c.canvas),GRAY_LT:strip(c.border),GRAY_TXT:strip(s.textMuted),DARK_TXT:strip(c.dark),WHITE:strip(c.white),GREEN:strip(c.green),NEUTRAL_300:strip(n.neutral300),NEUTRAL_400:strip(n.neutral400),NEUTRAL_500:strip(n.neutral500),INFO_SURFACE:strip(s.infoSurface),WARNING_SURFACE:strip(s.warningSurface),SUCCESS_SURFACE:strip(s.successSurface),DANGER_SURFACE:strip(s.dangerSurface),LOGO:d.logo,LOGO_W:.95,LOGO_H:.95*(item.intrinsicHeight/item.intrinsicWidth),FONT:d.font,FONT_FALLBACK:d.fontFallback,CHART_COLORS:brand.charts.categorical.map(strip)}); }
function emailTheme() { return Object.freeze({ ...brand.email, font:brand.typography.email, customerIdentity:brand.audiences.customer.label, internalIdentity:brand.audiences.internal.label, internalFooter:audience('internal'), customerFooter:audience('customer') }); }
module.exports = Object.freeze({ ...brand, logo, audience, documentTheme, officeTheme, emailTheme });
