'use strict';
const path=require('path'),PptxGenJS=require('pptxgenjs'),brand=require('../shared/brand-system');
const theme=brand.officeTheme(),money=(n,c)=>`${c||'USD'} ${Math.round(Number(n)||0).toLocaleString('en-US')}`;
function addChrome(slide,title,draft){slide.background={color:theme.WHITE};slide.addShape('rect',{x:0,y:0,w:theme.W,h:.12,fill:{color:theme.CYAN},line:{color:theme.CYAN}});slide.addText(title,{x:.45,y:.25,w:8.8,h:.35,fontFace:theme.FONT,fontSize:20,bold:true,color:theme.NAVY});slide.addText(brand.audience('customer'),{x:.45,y:5.28,w:9.1,h:.15,fontFace:theme.FONT,fontSize:7,color:theme.GRAY_TXT,align:'right'});if(draft)slide.addText('DRAFT — NOT READY FOR CUSTOMER SHARING',{x:5.5,y:.28,w:4,h:.24,fontFace:theme.FONT,fontSize:9,bold:true,color:theme.RED,align:'right'});}
function addCover(pptx,story,draft){const s=pptx.addSlide();s.background={color:theme.NAVY};s.addImage({path:path.join(__dirname,'../../public',brand.logo('logoNegative')),x:.55,y:.45,w:theme.LOGO_W,h:theme.LOGO_H});s.addText('EXECUTIVE BUSINESS CASE',{x:.65,y:1.7,w:8.7,h:.35,fontFace:theme.FONT,fontSize:15,bold:true,color:theme.CYAN,charSpacing:2});s.addText(story.meta.customer,{x:.65,y:2.2,w:8.7,h:.75,fontFace:theme.FONT,fontSize:32,bold:true,color:theme.WHITE});s.addText(`${story.meta.solution} · ${String(story.meta.generatedAt).slice(0,10)}`,{x:.65,y:3.1,w:8.7,h:.35,fontFace:theme.FONT,fontSize:14,color:'C7D2D9'});if(draft)s.addText('DRAFT — NOT READY FOR CUSTOMER SHARING',{x:.65,y:4.55,w:8.7,h:.35,fontFace:theme.FONT,fontSize:13,bold:true,color:'FF8A72'});}
async function buildExecutivePptx(report,{internalDraft=false}={}){const story=report.story||report,pptx=new PptxGenJS();pptx.defineLayout({name:'CI',width:theme.W,height:theme.H});pptx.layout='CI';pptx.author='Cloud Inventory';pptx.company='Cloud Inventory';pptx.subject='Customer ROI executive review';pptx.title=`Executive Business Case — ${story.meta.customer}`;pptx.lang='en-US';pptx.theme={headFontFace:theme.FONT,bodyFontFace:theme.FONT,lang:'en-US'};addCover(pptx,story,internalDraft);
 let s=pptx.addSlide();addChrome(s,'Executive Value Story',internalDraft);[['Why Change',story.threeWhys.whyChange],['Why Now',story.threeWhys.whyNow],['Why Cloud Inventory',story.threeWhys.whyCloudInventory]].forEach(([label,x],i)=>{const y=1+i*1.25;s.addShape('roundRect',{x:.55,y,w:8.9,h:1,rectRadius:.06,fill:{color:theme.GRAY_BG},line:{color:theme.GRAY_LT}});s.addText(label,{x:.75,y:y+.13,w:2,h:.22,fontFace:theme.FONT,fontSize:12,bold:true,color:theme.CYAN_DARK});s.addText(x.value,{x:2.4,y:y+.12,w:6.65,h:.52,fontFace:theme.FONT,fontSize:11,color:theme.DARK_TXT,breakLine:false});s.addText(x.status,{x:2.4,y:y+.7,w:6.5,h:.15,fontFace:theme.FONT,fontSize:7,color:theme.GRAY_TXT});});
 s=pptx.addSlide();addChrome(s,'Financial Case',internalDraft);const e=story.economics,metrics=[['Annual Customer Benefit',money(e.annualBenefit,story.meta.currency)],['Total Contract Benefit',money(e.totalContractBenefit,story.meta.currency)],['Modeled Customer Investment',money(e.totalContractInvestment,story.meta.currency)],['Net Economic Benefit',money(e.netEconomicBenefit,story.meta.currency)],['Contract ROI',e.contractRoi==null?'—':Math.round(e.contractRoi)+'%'],['NPV',money(e.npv,story.meta.currency)],['Payback',e.payback==null?'Not within term':Number(e.payback).toFixed(1)+' months'],['Customer-Supported Value',e.customerSupportedValuePct+'%']];metrics.forEach(([l,v],i)=>{const x=.55+(i%4)*2.3,y=1+Math.floor(i/4)*1.55;s.addShape('roundRect',{x,y,w:2.08,h:1.2,fill:{color:theme.GRAY_BG},line:{color:theme.GRAY_LT}});s.addText(l,{x:x+.12,y:y+.14,w:1.84,h:.3,fontFace:theme.FONT,fontSize:8,color:theme.GRAY_TXT});s.addText(v,{x:x+.12,y:y+.58,w:1.84,h:.35,fontFace:theme.FONT,fontSize:15,bold:true,color:theme.NAVY,fit:'shrink'});});
 if(report.chartData&&report.chartData.contractTimeline?.length){s=pptx.addSlide();addChrome(s,'Contract Value Over Time',internalDraft);const timeline=report.chartData.contractTimeline,labels=timeline.map(x=>x.label);s.addChart('line',[{name:'Cumulative benefit',labels,values:timeline.map(x=>x.benefit)},{name:'Cumulative investment',labels,values:timeline.map(x=>x.investment)},{name:'Cumulative net value',labels,values:timeline.map(x=>x.netValue)}],{x:.7,y:.85,w:8.65,h:3.65,showLegend:true,legendPos:'b',showTitle:false,showValue:false,showCatName:false,catAxisLabelFontFace:theme.FONT,catAxisLabelFontSize:10,valAxisLabelFontFace:theme.FONT,valAxisLabelFontSize:9,valGridLine:{color:theme.GRAY_LT,width:1},chartColors:[theme.CYAN,theme.ORANGE,theme.GREEN],showMarker:true,lineSize:2});s.addText(`Total contract ROI ${report.financials.contractRoi==null?'N/A':Math.round(report.financials.contractRoi)+'%'} · ${report.contract.months}-month term`,{x:.7,y:4.6,w:8.6,h:.28,fontFace:theme.FONT,fontSize:11,bold:true,color:theme.NAVY,align:'center'});}
 s=pptx.addSlide();addChrome(s,'Modeled Value Drivers',internalDraft);const drivers=(e.activeDrivers||[]).slice(0,5),max=Math.max(1,...drivers.map(d=>Number(d.annualValue)||0));drivers.forEach((d,i)=>{const y=.95+i*.72,w=5.1*(Number(d.annualValue)||0)/max;s.addText(d.label,{x:.55,y,w:2.3,h:.24,fontFace:theme.FONT,fontSize:10,color:theme.DARK_TXT});s.addShape('rect',{x:2.9,y:y+.02,w:5.1,h:.18,fill:{color:theme.GRAY_LT},line:{color:theme.GRAY_LT}});s.addShape('rect',{x:2.9,y:y+.02,w, h:.18,fill:{color:theme.CHART_COLORS[i]},line:{color:theme.CHART_COLORS[i]}});s.addText(money(d.annualValue,story.meta.currency),{x:8.15,y,w:1.25,h:.24,fontFace:theme.FONT,fontSize:10,bold:true,color:theme.NAVY,align:'right'});s.addText(d.status,{x:2.9,y:y+.27,w:5.8,h:.16,fontFace:theme.FONT,fontSize:7,color:theme.GRAY_TXT});});if(!drivers.length)s.addText('No modeled value drivers yet.',{x:.7,y:1.3,w:8.5,h:.5,fontFace:theme.FONT,fontSize:18,color:theme.GRAY_TXT,align:'center'});
 s=pptx.addSlide();addChrome(s,'Solution Alignment & Joint Next Steps',internalDraft);s.addText(story.solutionAlignment.exists?`${story.solutionAlignment.products.join(', ')}${story.solutionAlignment.systemOfRecord?' · '+story.solutionAlignment.systemOfRecord:''}`:'Solution alignment to validate.',{x:.65,y:.95,w:8.7,h:.55,fontFace:theme.FONT,fontSize:14,bold:true,color:theme.NAVY});s.addText(`ROI modeling assumption: ${story.implementationContext.modelingMonths||0} months to implementation/go-live. This is not a delivery commitment.`,{x:.65,y:1.6,w:8.7,h:.45,fontFace:theme.FONT,fontSize:10,color:theme.GRAY_TXT});const steps=story.nextSteps.items||[];s.addText(steps.length?steps.slice(0,5).map(x=>({text:`• ${x.milestone} — ${x.owner}${x.dueDate?' — '+x.dueDate:''}`,options:{bullet:false,breakLine:true}})):[{text:story.nextSteps.message||'Joint next steps to validate.',options:{breakLine:true}}],{x:.75,y:2.35,w:8.4,h:2,fontFace:theme.FONT,fontSize:12,color:theme.DARK_TXT,breakLine:true});
 if((story.customerProof||[]).length){s=pptx.addSlide();addChrome(s,'Approved Customer Proof',internalDraft);(story.customerProof||[]).slice(0,3).forEach((p,i)=>s.addText(`${p.customerName||p.name||'Approved peer evidence'}\n${p.outcome||p.summary||''}`,{x:.65,y:1+i*1.15,w:8.7,h:.8,fontFace:theme.FONT,fontSize:11,color:theme.DARK_TXT,breakLine:true}));}
 return pptx.write({outputType:'nodebuffer'});
}
module.exports={buildExecutivePptx};
