'use strict';

/* Dependency-free, in-memory PDF writer. It uses standard PDF fonts and
   vector drawing commands, so it is reliable on Render and leaves no temp
   files behind. */
const fs=require('fs'),path=require('path'),zlib=require('zlib'),brand = require('../shared/brand-system');
const theme = brand.documentTheme('customer');
const PAGE = { w: 612, h: 792, left: 50, right: 562, top: 64, bottom: 54 };
const rgb = hex => { const v=String(hex).replace('#',''); return [0,2,4].map(i=>parseInt(v.slice(i,i+2),16)/255); };
const color = hex => rgb(hex).map(v=>v.toFixed(3)).join(' ');
const esc = value => String(value == null ? '' : value)
  .replace(/[–—]/g,'-').replace(/[‘’]/g,"'").replace(/[“”]/g,'"').replace(/·/g,'|')
  .normalize('NFKD').replace(/[^\x20-\x7E\xA9]/g,'')
  .replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)').replace(/[\r\n]+/g,' ');
const money = (value,currency) => `${currency} ${Math.round(Number(value)||0).toLocaleString('en-US')}`;
const pct = value => value == null ? 'N/A' : `${Math.round(Number(value))}%`;
const wrap = (value,max=78) => { const words=String(value||'').split(/\s+/).filter(Boolean),out=[];let line='';for(const word of words){if((line+' '+word).trim().length>max&&line){out.push(line);line=word;}else line=(line+' '+word).trim();}if(line)out.push(line);return out.length?out:['']; };

function builder(report,{internalDraft=false}={}){
  const pages=[];let ops=[],y=PAGE.h-PAGE.top,pageNo=0;
  const addPage=(title='')=>{if(ops.length)pages.push(ops.join('\n'));ops=[];pageNo++;y=PAGE.h-PAGE.top;ops.push(`${color(theme.accent)} RG 2 w ${PAGE.left} ${PAGE.h-35} m ${PAGE.right} ${PAGE.h-35} l S`);ops.push(`q 72 0 0 25 ${PAGE.left} ${PAGE.h-30} cm /Im1 Do Q`);if(title)ops.push(`BT /F2 16 Tf ${color(theme.heading)} rg ${PAGE.left} ${y} Td (${esc(title)}) Tj ET`),y-=30;if(internalDraft)ops.push(`BT /F2 8 Tf ${color(theme.danger)} rg 360 ${PAGE.h-28} Td (DRAFT - NOT READY FOR CUSTOMER SHARING) Tj ET`);};
  const ensure=h=>{if(y-h<PAGE.bottom){footer();addPage();}};
  const footer=()=>{ops.push(`${color(theme.border)} RG .5 w ${PAGE.left} 35 m ${PAGE.right} 35 l S`);ops.push(`BT /F1 7 Tf ${color(theme.muted)} rg ${PAGE.left} 22 Td (${esc(brand.audience(internalDraft?'internal':'customer'))}) Tj ET`);ops.push(`BT /F1 7 Tf ${color(theme.muted)} rg 520 22 Td (Page ${pageNo}) Tj ET`);};
  const text=(value,{size=10,bold=false,indent=0,width=86,leading=size+4,colorHex=theme.body}={})=>{const lines=wrap(value,width);for(const line of lines){ensure(leading+4);ops.push(`BT /${bold?'F2':'F1'} ${size} Tf ${color(colorHex)} rg ${PAGE.left+indent} ${y} Td (${esc(line)}) Tj ET`);y-=leading;}return lines.length;};
  const heading=value=>{ensure(34);y-=5;text(value,{size:14,bold:true,width:60,colorHex:theme.heading,leading:18});ops.push(`${color(theme.accent)} RG 1.5 w ${PAGE.left} ${y+5} m ${PAGE.right} ${y+5} l S`);y-=12;};
  const metric=(label,value,x,top,w=118)=>{ops.push(`${color(theme.canvas)} rg ${x} ${top-54} ${w} 54 re f`);ops.push(`${color(theme.border)} RG .5 w ${x} ${top-54} ${w} 54 re S`);ops.push(`BT /F1 7 Tf ${color(theme.muted)} rg ${x+8} ${top-15} Td (${esc(label.toUpperCase())}) Tj ET`);ops.push(`BT /F2 13 Tf ${color(theme.heading)} rg ${x+8} ${top-39} Td (${esc(value)}) Tj ET`);};
  const tableRow=(cells,widths,{header=false}={})=>{ensure(24);const top=y+5;let x=PAGE.left;const fill=header?theme.tableHeader:'#FFFFFF';if(header)ops.push(`${color(fill)} rg ${PAGE.left} ${top-20} ${PAGE.right-PAGE.left} 22 re f`);cells.forEach((cell,i)=>{ops.push(`BT /${header?'F2':'F1'} ${header?8:8} Tf ${color(header?'#FFFFFF':theme.body)} rg ${x+5} ${top-14} Td (${esc(cell)}) Tj ET`);x+=widths[i];});ops.push(`${color(theme.border)} RG .4 w ${PAGE.left} ${top-21} m ${PAGE.right} ${top-21} l S`);y-=22;};

  addPage();
  y=590;ops.push(`BT /F2 15 Tf ${color(theme.accent)} rg ${PAGE.left} ${y} Td (EXECUTIVE BUSINESS CASE) Tj ET`);y-=55;text(report.customer.name,{size:28,bold:true,width:29,leading:34,colorHex:theme.heading});y-=20;text(`${report.opportunity.solution} | ${report.contract.months}-month value case`,{size:13,width:65,colorHex:theme.muted});y-=80;text(`Prepared by ${report.opportunity.preparedBy||'Cloud Inventory'} | ${report.generatedAt.slice(0,10)}`,{size:10,width:70});footer();

  addPage('Executive value story');
  for(const [label,item] of [['Why change',report.executiveSummary.threeWhys.whyChange],['Why now',report.executiveSummary.threeWhys.whyNow],['Why Cloud Inventory',report.executiveSummary.threeWhys.whyCloudInventory]]){text(label,{size:11,bold:true,width:70,colorHex:theme.accessibleAccent});text(item.value,{size:10,width:86});text(item.status,{size:8,width:90,colorHex:theme.muted});y-=10;}
  ensure(195);heading('Financial summary');const f=report.financials,top=y;metric('Annual benefit',money(f.annualBenefit,report.currency),50,top,120);metric('Contract investment',money(f.totalInvestment,report.currency),180,top,120);metric('Net value',money(f.netValue,report.currency),310,top,120);metric('Contract ROI',pct(f.contractRoi),440,top,122);y-=75;metric('Contract benefit',money(f.totalBenefit,report.currency),50,y,160);metric('NPV',money(f.npv,report.currency),226,y,160);metric('Payback',f.paybackMonths==null?'Not in term':`${f.paybackMonths.toFixed(1)} months`,402,y,160);y-=75;footer();

  addPage('Contract value over time');
  const chartTop=y-20,chartBottom=chartTop-180,chartLeft=74,chartRight=548,max=Math.max(1,...report.chartData.contractTimeline.flatMap(d=>[d.benefit,d.investment,Math.max(0,d.netValue)]));ops.push(`${color(theme.border)} RG .5 w ${chartLeft} ${chartBottom} m ${chartLeft} ${chartTop} l ${chartRight} ${chartTop} l S`);
  const series=[['benefit',theme.accent],['investment',theme.warning],['netValue',theme.success]];series.forEach(([key,c])=>{let prior=null;report.chartData.contractTimeline.forEach((d,i)=>{const x=chartLeft+(i+1)*(chartRight-chartLeft)/(report.chartData.contractTimeline.length+1),cy=chartBottom+Math.max(0,d[key])/max*(chartTop-chartBottom);if(prior)ops.push(`${color(c)} RG 2 w ${prior.x} ${prior.y} m ${x} ${cy} l S`);ops.push(`${color(c)} rg ${x-2} ${cy-2} 4 4 re f`);prior={x,y:cy};});});
  report.chartData.contractTimeline.forEach((d,i)=>{const x=chartLeft+(i+1)*(chartRight-chartLeft)/(report.chartData.contractTimeline.length+1);ops.push(`BT /F1 8 Tf ${color(theme.muted)} rg ${x-15} ${chartBottom-17} Td (${esc(d.label)}) Tj ET`);});y=chartBottom-38;text('Cumulative benefit', {size:9,bold:true,indent:10,colorHex:theme.accent,width:30});y+=13;text('Cumulative investment', {size:9,bold:true,indent:145,colorHex:theme.warning,width:30});y+=13;text('Cumulative net value', {size:9,bold:true,indent:310,colorHex:theme.success,width:30});y-=16;
  heading('Contract-year detail');tableRow(['Year','Benefit','Investment','Net value','Cumulative ROI'],[45,116,116,116,119],{header:true});for(const row of report.years)tableRow([String(row.year),money(row.benefit,report.currency),money(row.investment,report.currency),money(row.netValue,report.currency),pct(row.cumulativeRoi)],[45,116,116,116,119]);footer();

  addPage('Value drivers and assumptions');
  heading('Annual value composition');const maxBenefit=Math.max(1,...report.benefits.map(x=>x.annualValue));for(const item of report.benefits.slice(0,10)){ensure(30);text(item.label,{size:9,bold:true,width:52});const barY=y+5,w=210*item.annualValue/maxBenefit;ops.push(`${color(theme.border)} rg 260 ${barY} 210 8 re f`);ops.push(`${color(theme.accessibleAccent)} rg 260 ${barY} ${w.toFixed(2)} 8 re f`);ops.push(`BT /F2 8 Tf ${color(theme.heading)} rg 475 ${barY-1} Td (${esc(money(item.annualValue,report.currency))}) Tj ET`);y-=9;}
  heading('Model assumptions');tableRow(['Contract term',`${report.contract.months} months`],[180,332],{header:true});tableRow(['Implementation period',`${report.contract.implementationMonths} months`],[180,332]);tableRow(['Discount rate',`${(report.assumptions.discountRate*100).toFixed(1)}%`],[180,332]);tableRow(['ROI model version',String(report.assumptions.modelVersion||'Current')],[180,332]);tableRow(['Customer-supported value',`${report.assumptions.customerSupportedValuePct}%`],[180,332]);footer();

  addPage('Solution alignment and joint next steps');
  heading('Solution alignment');text(report.solutionFit.exists?`${report.solutionFit.products.join(', ')||report.opportunity.solution}${report.solutionFit.systemOfRecord?' | System of record: '+report.solutionFit.systemOfRecord:''}`:'Solution alignment remains to be validated.',{size:10,width:84});
  heading('Joint next steps');if(report.jointProjectPlan.items.length){for(const item of report.jointProjectPlan.items.slice(0,10))text(`- ${item.milestone} | ${item.owner}${item.dueDate?' | '+item.dueDate:''}`,{size:9,width:90});}else text(report.jointProjectPlan.message,{size:10,width:85});
  if(report.stakeholders.length){heading('Customer stakeholders');tableRow(['Name','Title'],[210,302],{header:true});for(const p of report.stakeholders.slice(0,12))tableRow([p.name,p.title],[210,302]);}footer();pages.push(ops.join('\n'));

  return makePdf(pages);
}

function pngRgb(file){const input=fs.readFileSync(file);if(input.subarray(1,4).toString()!=='PNG')throw new Error('Invalid logo PNG.');let offset=8,width=0,height=0,bit=0,type=0,idat=[];while(offset<input.length){const len=input.readUInt32BE(offset),name=input.subarray(offset+4,offset+8).toString(),data=input.subarray(offset+8,offset+8+len);offset+=12+len;if(name==='IHDR'){width=data.readUInt32BE(0);height=data.readUInt32BE(4);bit=data[8];type=data[9];}else if(name==='IDAT')idat.push(data);else if(name==='IEND')break;}if(bit!==8||type!==6)throw new Error('Logo PNG must be 8-bit RGBA.');const raw=zlib.inflateSync(Buffer.concat(idat)),stride=width*4,out=Buffer.alloc(width*height*3);let prior=Buffer.alloc(stride),pos=0,dst=0;const paeth=(a,b,c)=>{const p=a+b-c,pa=Math.abs(p-a),pb=Math.abs(p-b),pc=Math.abs(p-c);return pa<=pb&&pa<=pc?a:pb<=pc?b:c;};for(let row=0;row<height;row++){const filter=raw[pos++],scan=Buffer.from(raw.subarray(pos,pos+stride));pos+=stride;for(let i=0;i<stride;i++){const left=i>=4?scan[i-4]:0,up=prior[i]||0,ul=i>=4?prior[i-4]||0:0;if(filter===1)scan[i]=(scan[i]+left)&255;else if(filter===2)scan[i]=(scan[i]+up)&255;else if(filter===3)scan[i]=(scan[i]+Math.floor((left+up)/2))&255;else if(filter===4)scan[i]=(scan[i]+paeth(left,up,ul))&255;}for(let i=0;i<stride;i+=4){const a=scan[i+3]/255;out[dst++]=Math.round(scan[i]*a+255*(1-a));out[dst++]=Math.round(scan[i+1]*a+255*(1-a));out[dst++]=Math.round(scan[i+2]*a+255*(1-a));}prior=scan;}return{width,height,data:zlib.deflateSync(out)};}
function makePdf(pageStreams){const objects=[];const add=s=>{objects.push(s);return objects.length;};const font1=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>'),font2=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>'),logo=pngRgb(path.join(__dirname,'../../public',brand.logo(theme.logoRole))),image=add(Buffer.concat([Buffer.from(`<< /Type /XObject /Subtype /Image /Width ${logo.width} /Height ${logo.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /FlateDecode /Length ${logo.data.length} >>\nstream\n`,'binary'),logo.data,Buffer.from('\nendstream','binary')]));const pagesId=4;objects.push('PAGES_PLACEHOLDER');const pageIds=[];for(const stream of pageStreams){const content=add(`<< /Length ${Buffer.byteLength(stream,'binary')} >>\nstream\n${stream}\nendstream`);pageIds.push(add(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${PAGE.w} ${PAGE.h}] /Resources << /Font << /F1 ${font1} 0 R /F2 ${font2} 0 R >> /XObject << /Im1 ${image} 0 R >> >> /Contents ${content} 0 R >>`));}objects[pagesId-1]=`<< /Type /Pages /Kids [${pageIds.map(id=>`${id} 0 R`).join(' ')}] /Count ${pageIds.length} >>`;const catalog=add(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);const chunks=[Buffer.from('%PDF-1.4\n%CIROI\n','binary')],offsets=[0];let size=chunks[0].length;objects.forEach((obj,i)=>{offsets.push(size);const body=Buffer.isBuffer(obj)?obj:Buffer.from(obj,'binary'),chunk=Buffer.concat([Buffer.from(`${i+1} 0 obj\n`,'binary'),body,Buffer.from('\nendobj\n','binary')]);chunks.push(chunk);size+=chunk.length;});const xref=size;let trailer=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;for(let i=1;i<offsets.length;i++)trailer+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';trailer+=`trailer\n<< /Size ${objects.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;chunks.push(Buffer.from(trailer,'binary'));return Buffer.concat(chunks);}

module.exports = { buildExecutivePdf: builder };
