'use strict';
const path=require('path'),PptxGenJS=require('pptxgenjs'),brand=require('../shared/brand-system'),{pptFooter}=require('../shared/output-brand');
const T=brand.officeTheme(),logo=path.join(__dirname,'../../public',T.LOGO),clean=v=>String(v==null?'':v).slice(0,600);
function deck(title){const p=new PptxGenJS();p.defineLayout({name:'CI',width:T.W,height:T.H});p.layout='CI';p.author='Cloud Inventory';p.company='Cloud Inventory';p.title=title;p.theme={headFontFace:T.FONT,bodyFontFace:T.FONT,lang:'en-US'};return p;}
function chrome(s,title,audience){s.background={color:T.WHITE};s.addShape('rect',{x:0,y:0,w:T.W,h:.1,fill:{color:T.CYAN},line:{color:T.CYAN}});s.addImage({path:logo,x:.4,y:.25,w:T.LOGO_W,h:T.LOGO_H});s.addText(title,{x:.45,y:.82,w:8.9,h:.42,fontFace:T.FONT,fontSize:22,bold:true,color:T.NAVY});pptFooter(s,audience);}
function groups(plan){const gs=Array.isArray(plan.groups)?plan.groups:[],ms=Array.isArray(plan.milestones)?plan.milestones:[];return gs.length?gs:[...new Set(ms.map(x=>x.phase).filter(Boolean))].map((name,i)=>({id:`legacy-${i}`,name}));}
async function buildJppPptx(plan,{audience='customer'}={}){const p=deck(`Joint Project Plan — ${plan.company}`),ms=Array.isArray(plan.milestones)?plan.milestones:[],done=ms.filter(x=>x.status==='done').length,owner=x=>audience==='customer'?({rep:'Cloud Inventory',prospect:'Your team',joint:'Joint'}[x]||x):({rep:'Cloud Inventory',prospect:'Customer',joint:'Joint'}[x]||x);
 let s=p.addSlide();s.background={color:T.NAVY};s.addImage({path:logo,x:.55,y:.45,w:1.15,h:1.15*(T.LOGO_H/T.LOGO_W)});s.addText(audience==='internal'?'CONFIDENTIAL — INTERNAL USE ONLY':'JOINT PROJECT PLAN',{x:.6,y:1.55,w:8.8,h:.28,fontFace:T.FONT,fontSize:12,bold:true,color:T.CYAN,charSpacing:1.5});s.addText(clean(plan.title||'Joint Project Plan'),{x:.6,y:2,w:8.8,h:.65,fontFace:T.FONT,fontSize:30,bold:true,color:T.WHITE});s.addText(`${clean(plan.company)}${plan.target_close_date?' · Target close '+String(plan.target_close_date).slice(0,10):''}`,{x:.6,y:2.85,w:8.8,h:.35,fontFace:T.FONT,fontSize:14,color:T.NEUTRAL_300});s.addText(`${done} of ${ms.length} milestones complete`,{x:.6,y:3.5,w:8.8,h:.35,fontFace:T.FONT,fontSize:14,bold:true,color:T.CYAN});pptFooter(s,audience);
 const rows=[[{text:'Workstream',options:{bold:true,color:T.WHITE,fill:{color:T.NAVY}}},{text:'Milestone',options:{bold:true,color:T.WHITE,fill:{color:T.NAVY}}},{text:'Owner',options:{bold:true,color:T.WHITE,fill:{color:T.NAVY}}},{text:'Due',options:{bold:true,color:T.WHITE,fill:{color:T.NAVY}}},{text:'Status',options:{bold:true,color:T.WHITE,fill:{color:T.NAVY}}}]];for(const g of groups(plan)){for(const x of ms.filter(m=>m.groupId===g.id||(!m.groupId&&m.phase===g.name)))rows.push([clean(g.name),clean(x.title),clean(owner(x.owner)),x.dueDate?String(x.dueDate).slice(0,10):'—',x.status==='done'?'Complete':x.status==='in_progress'?'In progress':'Pending']);}
 s=p.addSlide();chrome(s,'Milestones',audience);s.addTable(rows.length>1?rows:[...rows,['—','No milestones yet','—','—','—']],{x:.45,y:1.4,w:9.1,h:3.5,colW:[1.35,4.15,1.15,1.15,1.3],fontFace:T.FONT,fontSize:9,border:{pt:.6,color:T.GRAY_LT},fill:T.WHITE,color:T.DARK_TXT,rowH:.35,margin:.06});return p.write({outputType:'nodebuffer'});}
async function buildStakeholderPptx({company,stakeholders=[]}){const p=deck(`Internal Stakeholder Map — ${company}`),s=p.addSlide();chrome(s,'Stakeholder Map — Internal', 'internal');s.addText(clean(company),{x:.45,y:1.25,w:9,h:.3,fontFace:T.FONT,fontSize:14,bold:true,color:T.CYAN_DARK});const rows=[[{text:'Name',options:{bold:true,color:T.WHITE,fill:{color:T.NAVY}}},{text:'Title',options:{bold:true,color:T.WHITE,fill:{color:T.NAVY}}},{text:'Role',options:{bold:true,color:T.WHITE,fill:{color:T.NAVY}}},{text:'Influence',options:{bold:true,color:T.WHITE,fill:{color:T.NAVY}}},{text:'Support',options:{bold:true,color:T.WHITE,fill:{color:T.NAVY}}},{text:'Engaged',options:{bold:true,color:T.WHITE,fill:{color:T.NAVY}}}],...stakeholders.map(x=>[clean(x.name),clean(x.title||'—'),clean(String(x.role||'').replaceAll('_',' ')),`${x.influence||0}/5`,`${x.support||0}/5`,x.engaged?'Yes':'No'])];s.addTable(rows.length>1?rows:[...rows,['No stakeholders yet','—','—','—','—','—']],{x:.45,y:1.7,w:9.1,h:3.25,colW:[1.65,2.15,1.65,1.15,1.15,1.15],fontFace:T.FONT,fontSize:9.5,border:{pt:.6,color:T.GRAY_LT},fill:T.WHITE,color:T.DARK_TXT,margin:.06});return p.write({outputType:'nodebuffer'});}
module.exports={buildJppPptx,buildStakeholderPptx};
